### ISSUE TITLE
Restore to system default node on nvm off

### ISSUE THREAD

**Issue by vkbansal** [coreybutler/nvm-windows#10]
Running `nvm off` does not restore `PATH` to previously installed nodejs

**Comment by coreybutler** [comment]
Closing. Obviously this never happened and this issue is outrageously outdated. 

For Googlers landing here:

This feature would require a snapshot of the PATH/version of any previous Node installations and it's simply more than this tool can/should handle. I question the value in this, since Node has proven to release and deprecate versions consistently. For example, if you installed NVM4W when Node 8 was released, then upgrade consistently for a few years, then decide to turn NVM off, you'll get a deprecated version of Node.
