### ISSUE TITLE
[Feature]: global tool registration

### ISSUE THREAD

**Issue by vbjay** [coreybutler/nvm-windows#1053]
### Description of the new feature / enhancement

Add a command that registers `npm  -g i <package>`  commands to run after installing a new version of  node so that yarn and such are installed globally again for that version.  

### Scenario when this would be used?

```shell
nvm instal lts
nvm use lts -reinstall-globals
```
Or even by default and add a switch to not do it.  If use detects switching between different versions it runs the registered global installs.  This way I don't have to keep reinstalling my global packages each version change.  I will know yarn and gulp and whatnot are installed.

**Comment by vbjay** [comment]
Could also just do a global list from nom and reinstall from the current version before a use does the switching.

**Comment by coreybutler** [comment]
This will not be coming to NVM4W due to the feature freeze. There is a hook system in [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) that supports the ability to install/link packages and respond to other events (like install). I'm not marking this as `consider for rt` because  the purpose of tagging issues that way is to make sure we don't lose them while building Runtime. Since we're already building this feature into Runtime, it'd be redundant.

**Comment by vbjay** [comment]
Thanks for the update.
