### ISSUE TITLE
exit status 145: Ŀ¼���ǿյġ�

### ISSUE THREAD

**Issue by livelyPeng** [coreybutler/nvm-windows#1059]
### What happened?

![image](https://github.com/coreybutler/nvm-windows/assets/32978177/b83b82ee-4075-4002-9cb6-158c238e1968)
I don't use version 1.1.7. I must use version 1.1.7 or higher; I want to know how to solve it?

### What did you expect to happen?

![image](https://github.com/coreybutler/nvm-windows/assets/32978177/e9451bb5-a62c-4688-a171-ea7ea482235b)
I don't use version 1.1.7. I must use version 1.1.7 or higher; I want to know how to solve it?

### Version

1.1.9

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
I don't use version 1.1.7. I must use version 1.1.7 or higher; I want to know how to solve it?
```

**Comment by coreybutler** [comment]
Have you looked at the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145)?

The error message is jumbled because it's not recognizing the text encoding properly (sometimes happens on non-English Windows versions).

v1.1.9 is pretty old. I encourage you to upgrade to v1.1.11. The debugging in the latest version is far superior to v1.1.9.

**Comment by livelyPeng** [comment]
@coreybutler Thank you, give it a try

**Comment by livelyPeng** [comment]
@coreybutler https://github.com/coreybutler/nvm-windows/issues/1060 Could you please show me ; Thank you,
