### ISSUE TITLE
[Issue]: The "no-install" variant of this software does not work for several reasons.

### ISSUE THREAD

**Issue by uap-universe** [coreybutler/nvm-windows#1074]
### What happened?

1. After unzipping the "no-install" variant, the software does not work, unless you find out that you need to copy and adapt the settings.txt from the examples directory (no mention about this in the README)
2. After adding the settings.txt, installation works, but nodejs is not installed in the `path` but in the subdirectory of `root`. (if that's intended, then what exactly is `path` for? Again: no documentation.)
3. nvm use does not work without administrator privileges (this defeats the whole purpose of a no-install distribution, because you usually want that, because you don't want to (or cannot) install something as admin.
4. It's entirely unclear what `nvm use` actually does, because it apparently does *not* add the directory of the node installation to PATH. 

### What did you expect to happen?

1. Unzipping the software should be enough to run it. If it's not, running the software should either create a default (working) settings, prompt for additional settings, or terminate with a reference to the manual where to read about settings that have to be created.
2. I expected the nodejs installation to be installed into the nodejs directory I have specified with the `path` setting. But that might be just a misinterpretation. In any case, settings shall be documented in the README.
3. nvm should not request admin privileges where it doesn't need to. A user only installation and use of the software should be possible.
4. The effect of `nvm use` should be, that I can run the node executable from anywhere in my system - in other words: the path of the nodejs installation that is going to be used, should be added to the PATH variable.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

None

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Standard Use, Non-Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
is not using admin or elevated rights.
Error getting console handle: Der Vorgang wurde erfolgreich beendet.
Windows Version: 10.0 (Build 22621)

Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Development\Software\nvm\nvm.exe
NVM4W Settings:     C:\Development\Software\nvm\settings.txt
NVM_HOME:           C:\Development\Software\nvm
NVM_SYMLINK:        .
Node Installations: C:\Development\Software\nvm

Total Node.js Versions: 1
Active Node.js Version: none
(run "nvm use <version>" to activate a version)

PROBLEMS DETECTED
-----------------
Another Node.js installation is blocking NVM4W installations from running. Please uninstall the conflicting version or update the PATH environment variable to assure "." precedes "C:\Development\Software\nvm\v18.19.0".

The NVM4W symlink (.) was not found in the PATH environment variable.

NVM_SYMLINK (.) is not a valid symlink.

Connection type cannot be determined: dial tcp [::1]:80: connectex: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?

The problem reported by nvm debug is maybe due to my manual addition of the nodejs installation to PATH. I don't see why this should be a problem. It is extremely interesting, that the software identifies the installation it has installed previously as a conflicting installation. That should not happen.

**Comment by coreybutler** [comment]
To be clear, the no-install option is not a _variant_ of the application. It doesn't ship with an installer, but the app still needs to be installed in order to run. The no-install option is for people who need to manually create their own installers, such as a custom package to roll out via Active Directory.

Did you just skim the `README`, or did you read the [no-install/manual guide](https://github.com/coreybutler/nvm-windows/wiki#manual-installation)? It is linked from the `README` (shown here):

<img width="668" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/83929141-ba0c-4cf7-a646-2838c7c3443b">

---

The docs clearly state you need to create a `settings.txt` file and provide a link to the example:

<img width="764" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/ef808286-1d1a-4ed3-9622-be9948e4152f">

---

It is _expected_ that physical node installations are stored in the root, not in the `PATH`. The `NVM_SYMLINK` is supposed to be in the `PATH`. The `NVM_SYMLINK` changes when `nvm use` is run, relinking to the appropriate physical installation directory. This is spelled out in the `README` as the major distinction of this tool (https://github.com/coreybutler/nvm-windows#bulb-whats-the-big-difference):

<img width="680" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/59569029-72a3-4c9a-b38c-a53b2ebb269d">

---

_Windows_ requires elevated privileges to symlink directories. Administrators have these privileges, as does anyone who has developer mode enabled. You can also explicitly grant symlink permissions to trusted users. Microsoft has more information about this [here](https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links). There are also more tips in the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) section of this project.

Please remember that installing multiple versions of Node.js is exactly that... _installing software on the OS_. Microsoft has safeguards in place to protect against unauthorized installations. This tool is designed to find a balance between these restrictions and developer freedom, but every user/organization's threat tolerance is different. 

If you are seeking more enterprise-specific features, I recommend following the news for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime), the successor software we're currently building.

---

As per your last point about how the `PATH` should point to the Node installation: This was how one of the very first alpha editions handled it. It proved to be dangerous. If something fails or there is an odd path (custom character) added to the `PATH`, or even if the path is long, it can truncate the `PATH` environment variable leading to system-wide loss of other applications (or worse, system failure). Constantly changing the `PATH` whenever a different version of Node is required can cause race conditions between apps too. Throughout the issue history in this repo, I refer to this as `PATH` thrashing. This is why a symlink is used instead. We can "thrash" the symlink because it is limited to the NVM4W app, isolated from the rest of the system.

Additionally, the debugger appears to be thrown off by the invalid `settings.txt`. Use the example settings file as a guide.
