### ISSUE TITLE
I can't update nvm-windows

### ISSUE THREAD

**Issue by lucasdnr** [coreybutler/nvm-windows#1075]
### What happened?

I had version 1.1.7 installed so I tried to update to 1.1.12
- I have uninstalled version 1.1.7, I tried to access it through the console but it didn't find the nvm and the folder was also deleted, which I considered the uninstall process to be successful
- Downloaded and installed the last version from https://github.com/coreybutler/nvm-windows/releases/download/1.1.12/nvm-setup.exe
- After the installation process, I opened the console and the version is still 1.1.7
```
nvm version
1.1.7
```
It doesn't have any new features from 1.1.12

### What did you expect to happen?

Update to 1.1.12

### Version

1.1.7

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Debug Output

```Shell
No Logs
```

**Comment by coreybutler** [comment]
It sounds like something didn't get uninstalled. Check your `PATH` to see if there is a duplicate entry. Also check the values of `NVM_HOME` and `NVM_SYMLINK`. If you're still seeing v1.1.7, it's being picked up from the `NVM_HOME` path.

**Comment by EzioMercer** [comment]
In my case it was because of another program with the name `herd` which also uses the `nvm` so my `Path` looked like this:

<img width="253" height="117" alt="Image" src="https://github.com/user-attachments/assets/fea7675a-4d7a-4023-80e9-c3d273cdde67" />

So I just moved the path for `nvm` of `herd` under the `%NVM_*%` variables

<img width="271" height="118" alt="Image" src="https://github.com/user-attachments/assets/3172bf4a-a42d-4f05-9681-68d0a73994cc" />

And now I'm getting the right version of `nvm`

---

P.S. For future readers. The `Windows` uses the `Path` to execute the global "scripts"

Let's say you are running some `useful-program` just typing its name in command line. The `Windows` will look for every path in the `Path` to see if this directory has the file with the name `useful-program` if it finds it will not look to other `path` so the first one wins
