### ISSUE TITLE
[Issue]: NVM Install via batch file

### ISSUE THREAD

**Issue by LorenDorez** [coreybutler/nvm-windows#1091]
### What happened?

Using a batch file to install and setup nvm and a few other bells and whistles but seems you cant use nvm right after install in the same batch files.

### What did you expect to happen?

Below is the basics of the batch file and a snapshot of the issue

```
ECHO Install NVM For Windows...
winget install nvm-windows

ECHO Installing v20.10.0 ...
%AppData%\nvm\nvm.exe install 20.10.0

%AppData%\nvm\nvm.exe use 20.10.0
%AppData%\nvm\nvm.exe current
%AppData%\nvm\nvm.exe debug
```

![image](https://github.com/coreybutler/nvm-windows/assets/3706392/65618466-dbe9-498d-baf5-a25c58784807)

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
Install NVM For Windows...
Found NVM for Windows [CoreyButler.NVMforWindows] Version 1.1.11
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-setup.exe
  ██████████████████████████████  5.46 MB / 5.46 MB
Successfully verified installer hash
Starting package install...
Successfully installed


Set temp variable NVM_HOME...

Installing v20.10.0 ...
Downloading node.js version 20.10.0 (64-bit)...
Extracting node and npm...
Complete
npm v10.2.3 installed successfully.


Installation complete. If you want to use this version, type

nvm use 20.10.0


Setting to use v20.10.0...
Now using node v20.10.0 (64-bit)
No current version. Run 'nvm use x.x.x' to set a version.
Running NVM for Windows with administrator privileges.

C:\WINDOWS\System32\cmd.exe
NVM4W Version:      1.1.11
NVM4W Path:         UNKNOWN: not found
NVM4W Settings:     C:\Users\loren-dorez\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\loren-dorez\AppData\Roaming\nvm
NVM_SYMLINK:        .
Node Installations: C:\Users\loren-dorez\AppData\Roaming\nvm

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

PROBLEMS DETECTED
-----------------
"C:\WINDOWS\System32\cmd.exe" is not an officially supported shell. Some features may not work as expected.


The NVM4W symlink (.) was not found in the PATH environment variable.


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

C:\WINDOWS\System32\cmd.exe
NVM4W Version:      1.1.11
NVM4W Path:         UNKNOWN: not found
NVM4W Settings:     C:\Users\loren-dorez\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\loren-dorez\AppData\Roaming\nvm
NVM_SYMLINK:        .
Node Installations: C:\Users\loren-dorez\AppData\Roaming\nvm

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

PROBLEMS DETECTED
-----------------
"C:\WINDOWS\System32\cmd.exe" is not an officially supported shell. Some features may not work as expected.


The NVM4W symlink (.) was not found in the PATH environment variable.


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?

any help is appreciated

**Comment by coreybutler** [comment]
We don't maintain the winget installer. It looks like it's not updating the `PATH` though. See https://github.com/coreybutler/nvm-windows/wiki.

**Comment by LorenDorez** [comment]
If I open a new command prompt everything works just fine. I just can't use nvm in the same shell I install it with. 

I'll see it if I can manually set the path in my shell as see if that helps. I had to do that for %NVM_HOME%

**Comment by sitiom** [comment]
> We don't maintain the winget installer. It looks like it's not updating the `PATH` though. See [coreybutler/nvm-windows/wiki](https://github.com/coreybutler/nvm-windows/wiki).

You actually do, though 😅: https://github.com/coreybutler/nvm-windows/blob/master/.github/workflows/winget.yml. About Winget, It's just running the installer you provided, which means there is no magic happening on the Winget side behind the scenes.

About the workflow error: https://github.com/coreybutler/nvm-windows/actions/runs/6962150119/job/18984279583, can you try manually syncing https://github.com/coreybutler/winget-pkgs up-to-date and rerunning the failed workflow? I think the reason for the failure is due to an outdated fork.

**Comment by coreybutler** [comment]
@sitiom as you know, that workflow has never actually worked. Truthfully, it's more hassle than it's worth, especially since our focus is on [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime). I don't really want users installing from winget with this tool because it just keeps adding issues I don't really have time to deal with. We're planning proper support for winget with Runtime (as well as other install options), so that's where my focus is.

@LorenDorez The innosetup installer sometimes works in the shell you install in and sometimes doesn't. It's an extremely annoying issue with innosetup+windows where Windows isn't signaling completion properly, so things sometimes get updated out of order (seems worst on Windows 10, but happens on 11 and servers too). That's why the docs recommend restarting the shell. So, for your case, you probably will need to manually specify the env vars for the shell you're running in. I'm sorry for that... I wish I had a better answer for you.

**Comment by sitiom** [comment]
> @sitiom as you know, that workflow has never actually worked.

From the workflow:
- [Failed attempt #1](https://github.com/coreybutler/nvm-windows/actions/runs/6962150119/attempts/1) was because `nvm-setup.exe` didn't exist at the time.
- [Failed attempt #2](https://github.com/coreybutler/nvm-windows/actions/runs/6962150119/attempts/2) is because of an outdated fork

Both issues are easily actionable.

> Truthfully, it's more hassle than it's worth, especially since our focus is on [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime). I don't really want users installing from winget with this tool because it just keeps adding issues I don't really have time to deal with.

Like I said, Winget runs the official installer, which means that the issues should not come from the Winget side.

You can try out the thing I suggested above and see if it works. It only takes a minute of your time:

> can you try manually syncing [coreybutler/winget-pkgs](https://github.com/coreybutler/winget-pkgs) up-to-date and rerunning the failed workflow? I think the reason for the failure is due to an outdated fork.

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
bump

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
Bump

**Comment by sitiom** [comment]
bump

**Comment by coreybutler** [comment]
I got caught up in other issues (Node downloads failing). The official installer uses InnoSetup. Unfortunately, InnoSetup doesn't have a way to properly determine when the install is complete (yes, really) before exiting. As a result, this can cause a race condition, resulting in the behavior experienced. The only resolution is to create an alternative installer. I don't have time to rebuild the installer. This is why, for custom installs, I recommend scripting around [the manual approach](https://github.com/coreybutler/nvm-windows/wiki#manual-installation).

In [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) (the successor project), we have a completely new installer that isn't reliant on InnoSetup.

In the meantime, the best approach is to download nvm-noinstall.zip, extract the contents, and script your batch file according to the guide linked above.
