### ISSUE TITLE
"nvm list available" doesn't fails with error 404

### ISSUE THREAD

**Issue by lashchev** [coreybutler/nvm-windows#1095]
### What happened?

Downloaded and used the latest NVM4W installer on the fresh Win11 machine today.
In the admin console, `nvm list available` fails with the following error:

> Error retrieving "https://nodejs.org/dist/latest-available/SHASUMS256.txt": HTTP Status 404
Such a page indeed doesn't exist.

`nvm install` works fine.

### What did you expect to happen?

Expected a list of versions available to install

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

None

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrator: Command Prompt (Admin) - nvm  debug
Windows Version: 10.0 (Build 22631)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\usr\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\usr\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\usr\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\usr\AppData\Roaming\nvm

Total Node.js Versions: 0
Active Node.js Version: none
(run "nvm use <version>" to activate a version)
NVM_SYMLINK does not exist yet. This is auto-created when "nvm use" is run.

IPv6 is enabled. This can slow downloads significantly.

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
Are you sure you ran `nvm list available`? Could you have inadvertently run `nvm install list-available`? I ask because that's the only way I can reproduce the error with that exact URL. SHASUMS are only retrieved during the install process, so there isn't another time when that would be requested.

Here's `nvm install list-available` (which should fail since there is no alias called `list-available`) followed by `nvm list available` (which should display a table).

<img width="683" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/ce2e641d-81db-49b5-bcb6-97b08f583e14">

**Comment by Leozw12** [comment]
Hi @coreybutler ，I have the same problem. It doesn't seem to use the version I specified to find node.
<img width="714" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/57360463/60c633f9-cc0c-46f1-b675-16d15162f015">

**Comment by coreybutler** [comment]
@Leozw12 it looks like you're using a mirror instead of the official node releases. The mirror doesn't appear to have that file.
