### ISSUE TITLE
[Issue]: When Windows username contains umlaut the installer fails

### ISSUE THREAD

**Issue by TanerUnal** [coreybutler/nvm-windows#1097]
### What happened?

Installation directory of nvm installer is by default ".../Users/[USERNAME]/...". But when the Windows username contains umlaut character like ü/Ü, ö/Ö, ... the installer fails eventually. On command line it is visible that the umlaut character fails to be read correctly.

### What did you expect to happen?

Installer in all stages should be able to locate the Windows user folder even if the username contains umlaut characters like ü/Ü and ö/Ö.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11

### Which locale?

English

### Which shell are you running NVM4W in?

cmd

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No

### Anything else?

I forgot the exact stage this failure occurs, since I actually experienced this problem a few weeks ago and did a walkaround by changing the installation directory.

**Comment by tocram1** [comment]
#726
Pretty much any "special" character makes this issue appear, I cannot install any node version because my name has a "é"...
I never thought Windows and other apps would still have issues with basic UTF-8 or Unicode characters, but here we are!
Apparently this is a workaround to fix this issue, I am yet to try it though.
