### ISSUE TITLE
[Issue]: version changing and alternative try install.ps1 file miss issue

### ISSUE THREAD

**Issue by Praveenrsm** [coreybutler/nvm-windows#1118]
### What happened?

if i change the version it was getting sucess but if i check nvm -v it was getting the older version or if i clone this git https://github.com/coreybutler/nvm-windows.git install.ps1 file w
![Screenshot (60)](https://github.com/coreybutler/nvm-windows/assets/105163502/1d4a0164-52d9-4159-85ad-36ce2d2f0885)
as missing

### What did you expect to happen?

the version want to change or install.ps1 file i want to get 

### Version

1.1.11 or newer (Default)

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
PS C:\nvm> nvm on
nvm enabled
Now using node v20.11.1 (64-bit)
PS C:\nvm> nvm use 18
Now using node v18.19.1 (64-bit)
PS C:\nvm> nvm -v
1.1.12
```

### Debug Output

```Shell
i tried
```

### Anything else?

no

**Comment by coreybutler** [comment]
I don't see anything wrong here. You ran `nvm use 18`, which configured Node `18.19.1`. This is shown in the output of the debug command (`Active Node.js Version: v18.19.1`). 

_nvm_ -v gives you the version of NVM for Windows.
_node_ -v gives you the version of Node.

It appears you're expecting `nvm -v` to show the _Node_ version.

**Comment by Praveenrsm** [comment]
After I gave nvm use different version it was taking the older version 1.1
version is this not a issue

**Comment by coreybutler** [comment]
I'm sorry, but I'm not following what the problem is here. This is the output you presented:

```
PS C:\nvm> nvm on
nvm enabled
Now using node v20.11.1 (64-bit)
PS C:\nvm> nvm use 18
Now using node v18.19.1 (64-bit)
PS C:\nvm> nvm -v
1.1.12
```

That is what I would expect for the commands you ran. However; I think you should be running these instead:

```sh
PS C:\nvm> nvm use 18
Now using node v18.19.1 (64-bit)
PS C:\nvm> node -v
v18.19.1
```

I don't really understand why you're running `nvm -v` in the first place. 

We don't ship an install.ps1 file (never have). You can't run more than one version of nvm.exe on a system at a time. It looks like you upgraded NVM4W to v1.1.12. Upgrades overwrite prior versions. Maybe that's what the install.ps1 you have does... but I have no idea because I didn't create that file.

**Comment by Praveenrsm** [comment]
I didn't ran nvm -v at first it was in last.after I change the version it
was getting the older and the downloaded version was not changing to other
versions.
