### ISSUE TITLE
[Issue]: Cannot switch nodejs

### ISSUE THREAD

**Issue by AlexanderDash** [coreybutler/nvm-windows#1147]
### What happened?

C:\Users\alexa>nvm ls

    20.11.0
  * 16.20.2 (Currently using 64-bit executable)

C:\Users\alexa>nvm use 20
node v20.11.0 (64-bit) is not installed.

C:\Users\alexa>nvm use 20.11.0
node v20.11.0 (64-bit) is not installed.

why？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

### What did you expect to happen?

fix

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
.
```

**Comment by coreybutler** [comment]
Not enough info. Please run `nvm debug` and paste the results here.

**Comment by coreybutler** [comment]
I'm not sure how it got into this state, but run `nvm install 20 64` to force the 64-bit install.

The primary issue appears to be a user account lacking permission to use mklink (the underlying windows utility used to generate symlinks). See [permission issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145).

**Comment by coreybutler** [comment]
OK, so if the executable is actually 64 bit, then it is actually 64-bit. Detecting architecture of an executable is a bit of a hack and won't always work. Since there isn't direct arm support yet (there is a PR I plan to merge to support this), I suspect the architecture detection simply isn't accounting for arm.

There's not a lot I ca do about this immediately, but once arm support is added, I believe this issue will be resolved. I'll leave this open until the PR is merged and will readdress this after that is complete.

**Comment by Kamek437** [comment]
Same problem here. The system node always gets used, and I can't uninstall it and reinstall it through nvm because it's required by Visual Studio.

**Comment by coreybutler** [comment]
@Kamek437 run `nvm debug`. I suspect you'll get a problem showing that the version you installed through VS 2022 precedes NVM4W on the PATH. See the common issues if this is the case. If not, open a new issue.

**Comment by watch-activity** [comment]
I had the same problem today.
However, in my case, the cause was leftover files from uninstalling the original node.js.

The nodejs folder remained in the following location without being deleted, so the symbolic link that NVM for Windows was supposed to create was not created and the switch could not be made.
C:\Program Files\notejs

**Comment by Kamek437** [comment]
@coreybutler Right you are my friend, thank you.
