### ISSUE TITLE
Can't debug with IntelliJ

### ISSUE THREAD

**Issue by fresheneesz** [coreybutler/nvm-windows#116]
After updating node with nvm-windows, I can no longer successfully connect to a debugging session with IntelliJ. I first tried to start a normal (non remote) debugging session with a configuration that has worked many times before. A popup came up that asked me if I want to allow that program to use the internet, I accepted. This hasn't happened before when I've tried it - or perhaps I've been using the same version of node for so long i've forgot doing it before. The popup hasn't come up since in any subsequent tries. In any case, after accepting, intellij simply wouldn't connect to the node debugger and just sits there. 

I then tried to create a remote debugging session to the same effect. Any idea what might be happening?

I'm on windows 8 using node v5.1.0, nvm-windows 1.1.0, and IntellJ 12.

**Comment by fresheneesz** [comment]
Switching back to my old old node v0.10.29 allows my debugger to work again. Luckily the thing I'm working with doesn't need newer node, so I can work with this for now..

**Comment by coreybutler** [comment]
This is an issue with either IntelliJ or node, not NVM. Connecting to node/debugging doesn't pass through NVM at all, which is highlighted by the fact it works with an older version of node but not a newer version. I don't use IntelliJ, so I'm not sure what it's doing. Most debugging is done by connecting to a port, i.e. acting more like a client/server model.

I'd suggest looking at IntelliJ support. Also keep in mind that the node 5.X branch isn't considered stable, so you may want to try with 4.x to see if there is a difference.

**Comment by fresheneesz** [comment]
@coreybutler So I know that version 4.1.2 of node.js works when run in CentOS with my *windows* intellij 12 (via remote debugger). I would be very very surprised if node v4.1.2 in windows isn't compatible with intellij 12, but v4.1.2 in linux is.

**Comment by fresheneesz** [comment]
Wellllll I tried installing v0.10.40 via nvm (since my v0.10.29 version wasn't installed through nvm), and debugging works. Sooo I guess it probably isn't anything related to nvm. Thanks!

**Comment by coreybutler** [comment]
@fresheneesz You only mentioned v0.10.29, which is pre-io.js merger. The big difference between the node 0.x series and the 4.x series is a major upgrade to the V8 engine. There have been bugs with "stable" functionality since this... I personally ran into an issue where `util.inherits` failed... something that has worked for a long time on prior branches (had to do with ES2015). 

You mentioned jumping straight to the 5.x branch, which is an unstable branch on the bleeding edge of V8. The v4.x branch is considered stable. I'm suggesting you try out v4.x because, well, it's the first stable release post-io.js. You could also try v0.12.x, which is the last stable release pre-io.js. The take-away is you can determine if the major updates in io.js are the cause of this.

The other possibility is there is nothing wrong with node, but the API may have changed and IntelliJ hasn't caught up.

Hope that helps, and good luck!

**Comment by fresheneesz** [comment]
Thanks corey. I probably just need to upgrade my (now super old) version of IntelliJ ; )
