### ISSUE TITLE
[Issue]: SYMLINK create not working properly when username contains ^

### ISSUE THREAD

**Issue by LucasWongC** [coreybutler/nvm-windows#1160]
### What happened?

My windows username is ^Clox^
I installed nvm windows, installed node version 20.
When I try to `nvm use 20`, it says `Now using node v18.20.4 (64-bit)`, but it doesn't recogize node as a command.
I found out that SYMLINK dir was pointing to `C:\Users\Clox\AppData\Roaming\nvm\v20.16.0` instead of `C:\Users\^Clox^\AppData\Roaming\nvm\v20.16.0`

### What did you expect to happen?

I am expecting it to point exact location

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrator: Command Prompt - nvm  debug
Windows Version: 10.0 (Build 19045)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\^Clox^\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\^Clox^\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\^Clox^\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\^Clox^\AppData\Roaming\nvm

Total Node.js Versions: 1
Active Node.js Version: none
(run "nvm use <version>" to activate a version)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x868195]

goroutine 1 [running]:
main.checkLocalEnvironment()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:1144 +0x1c35
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:169 +0x80b
```

**Comment by LucasWongC** [comment]
Can I have any update on this?

**Comment by coreybutler** [comment]
I'll see what I can do, but this is a low priority.

Generally speaking, most apps don't support the caret in Windows usernames because it is the escape character for Windows command-line operations. It can lead to a lot of screwy behavior.

**Comment by Brett-Clifford** [comment]
Hey im having the same type of issues where with installing the symlink. But mine is deleting the folder i tell it to install in.

so far i can no longer see my user/documents folder and i have lost multiple other folders that no longer exist on my pc.

**Comment by LucasWongC** [comment]
just heads up on this to prevent autoclose :)

**Comment by coreybutler** [comment]
@Brett-Clifford I did not see your post (would have been better as a separate issue). You've likely already found an answer, but for anyone else stumbling across this, symlnks on Windows cannot exist before you create them. It is default _Windows_ behavior to remove the folder, because you cannot link to a target that already exists.

**Comment by coreybutler** [comment]
Just following up on @Brett-Clifford's issue... `mklink` won't actually delete the directory. This is part of NVM4W though. There is code to remove the target directory if it exists. This happens because the assumption is the user wants that to be the symlink target. The installer does everything it can to protect against this, but after installation, it is up to the user to control the settings.

I can see how this behavior can lead to a footgun, so I've added some logic to prevent deletion of directory if set as the symlink target. Right now, the code will just throw an error. If I have enough time, I will add a prompt so people can choose whether to remove the directory for their symlink or not.

I'm sorry this caused you problems with data loss.
