### ISSUE TITLE
npm not working for v5

### ISSUE THREAD

**Issue by erquhart** [coreybutler/nvm-windows#124]
I'm not seeing any errors, but when I run `nvm use 5.3.0`, the node files are available in the symlinked directory, but the npm files are not. Npm files are included for other versions (currently using 4.2.3 and 0.10.41).

**Comment by whitecolor** [comment]
Do you see thi version in `nvm list availalbe`? Is v5 is supported at all?

**Comment by coreybutler** [comment]
I cannot recreate this error on Windows 10 (i.e. works as expected).

@whitecolor - see #111.

**Comment by hellfrom** [comment]
`nvm-windows` currently doesn't show that it supports the latest version of nodejs and maybe that's why it's necessary to update `~node_modules/npm` ourselves.
In my case `node v.5.5.0` goes with `npm v.3.3.12`.
And I have `ENV PATH=C:\Users\Username\AppData\Roaming\npm;`
So I downloaded source files from npm repository - [npm 3.3.12](https://github.com/npm/npm/releases/tag/v3.3.12 "v.3.3.12")
And copied them to `C:\Users\Username\AppData\Roaming\npm\node_modules\npm`.
Finally I restarted PC - and everything started working

**Comment by coreybutler** [comment]
closing due to age (cleanup)
