### ISSUE TITLE
Support per-user target

### ISSUE THREAD

**Issue by tracker1** [coreybutler/nvm-windows#131]
Would be nice if this supported a per-user target path under `%LOCALAPPDATA%` that the user can put in a per-user path, so that it can be run without admin privs... this would require moving the node/npm directories on use command instead of symlinking, but would be more durable in enterprise environments that don't allow local admin.

**Comment by coreybutler** [comment]
You can already set your install path in the installer. Instead of specifying `C:\Program Files\nodejs`, you can specify whatever you want. Doing this will prevent some problems with directory permissions.

NVM for Windows was built on the [core premise](https://github.com/coreybutler/nvm-windows#whats-the-big-difference) of using symlinks. Moving files and directories back and forth could be painfully slow. Specifically, the global `node_modules` folder can be extensively large. I tried this initially, and it can take as long as a 2 minutes with lots of modules. It was an unacceptable latency.

I don't really see a problem with the symlinks in an enterprise environment, despite their requirement for local admin privileges. The whole point of locking down an enterprise environment is to prevent installation of software and limit capabilities. This problem would exist if users were just installing node directly, without NVM. NVM for Windows is not designed to circumnavigate these enterprise policies. It is designed to fill the inherent gap created by rapid release cycles. It is up to the enterprise to determine their policies.

With a few exceptions, most of the enterprises I work with grant developers local administrative rights, either directly on their computer or through an Active Directory group policy.
