### ISSUE TITLE
Latest release does not list node 4.2.6 LTS

### ISSUE THREAD

**Issue by SteveALee** [coreybutler/nvm-windows#142]
Title says it all! ;)

**Comment by SteveALee** [comment]
It is possible to install versions not listed: eg 4.2.6 or 5.5.0
These version are not listed my `nvm list available` but appear in the meta data URL

**Comment by coreybutler** [comment]
So you're saying you see it listed at https://github.com/coreybutler/nodedistro/blob/master/nodeversions.json, but it's not displaying on the screen when you run the command?

**Comment by SteveALee** [comment]
yes

![nvmlist](https://cloud.githubusercontent.com/assets/618922/12654615/bfd3d6ec-c5ec-11e5-9c16-9db7684dec85.png)

**Comment by coreybutler** [comment]
Are you behind a proxy? It should be showing up. Only thing I can think of is request caching.

**Comment by Jeff-Lewis** [comment]
It's in the 'all' list but not in stable or unstable.

**Comment by SteveALee** [comment]
I'm confused as nodejs website lists both as latest version to download, implying they are stable. Infact 5.5.0 is called stable.

**Comment by coreybutler** [comment]
4.2.6 is Long Term Support, whereas 5.5.0 is the latest stable release. It's a different way of versioning compared to the 0.x.x series.

NVM only shows two sections though, for now. I haven't had time to implement anything new in the menu/ui yet.

**Comment by SteveALee** [comment]
I meant I'm confused why those 2 versions are not in your stable list?

**Comment by coreybutler** [comment]
See issue #111 for reasoning.

**Comment by SteveALee** [comment]
But 4.2.6 is LTS and is not listed

**Comment by SteveALee** [comment]
Also see #111

**Comment by coreybutler** [comment]
4.2.6 is listed, so closing this out. For future reference related to version 1.1.0, the list is still dependent on [nodedistro](https://github.com/coreybutler/nodedistro). The distro list is updated every hour, so if a new release just came out, be patient. Alternatively, submit a PR ton the nodedistro repo to update the list. 

On rare occasion, the service that runs the update script disconnects before the process completes. So if it has been more than 90 minutes since a release (allowing 30 minutes for the retry service) and it still doesn't show up, it should be updated manually. I do my best to keep up with this, but I am not always online or available when this occurs.

**Comment by SteveALee** [comment]
Got it. Am happy that latest LTS version is now showing. Thanks
