### ISSUE TITLE
Cross user support

### ISSUE THREAD

**Issue by ganna-shmatova** [coreybutler/nvm-windows#152]
Seems like if an administrator installs nvm even in `C:/nvm`, other users can't use it. It is a bit odd. System variables contain nvm...

I tested it twice on Windows Server 2012 & on Windows 7 locally.

**Comment by coreybutler** [comment]
That's expected if the other users don't have administrative privileges. Unlike *nix environments, Windows requires administrative rights to create symlinks.

**Comment by ganna-shmatova** [comment]
Hmm.. not so sure that's correct. The second user on the 2012 server was an administrator. I will test locally and get back to you.

**Comment by ganna-shmatova** [comment]
@coreybutler nope, seems even if a user is an administrator on either systems it still says nvm is not a recognized command.

**Comment by coreybutler** [comment]
Not being able to use it and not recognizing the command are two different issues. If the user can't use it, the issue is in the permissions. If the command isn't recognized, that's different. In that case, assuming the NVM_SYMLINK and NVM_HOME paths are defined in the system variables, you may want to replace them with the actual paths. A few users have reported success with this approach using older versions of Windows.

I'm not targeting true Windows 7 support (reached EOL), but several users have made it work by replacing the variables with the actual path. I haven't looked into it, but I suspect Windows 7 is not properly expanding those variables, thus resulting in the executable being unrecognized.

**Comment by ganna-shmatova** [comment]
Alright, looks like changing `%NVM_HOME%` and `%NVM_SYMLINK%` in `PATH` variable to the hardcoded paths worked. Thanks!

Also sorry for not providing the exact error earlier. Derp.

**Comment by coreybutler** [comment]
Glad you got it working!
