### ISSUE TITLE
Can't install Version 4.4.5

### ISSUE THREAD

**Issue by naxmefy** [coreybutler/nvm-windows#171]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

it should install

### Actual Behavior

it doesn't

### Steps to reproduce the problem:

try to install version 4.4.5

### Console Log

```
Version 4.4.5 is not available. If you are attempting to download a "just released" version,
it may not be recognized by the nvm service yet (updated hourly). If you feel this is in error and
you know the version exists, please visit http://github.com/coreybutler/nodedistro and submit a PR.
```

### seems....

...that http://github.com/coreybutler/nodedistro is deprecated. Does nvm-winows use https://nodejs.org/download/release/index.json?

**Comment by coreybutler** [comment]
The switch hasn't been made yet.

The most current **release** of NVM4W is `1.1.0`. The master branch contains `1.1.1`, but I haven't had a chance to run the build yet, thus no release. 

You have three choices for now:

1) Submit a PR to nodedistro and I'll merge it.... or just wait about 10 minutes and I'll add it myself.
2) Compile 1.1.1 on your own. 
3) Wait for me to release 1.1.1.... but that will likely be at least 2 weeks (I'm swamped speaking at conferences until mid-June).

I'm closing this since the best place for it is still in the nodedistro repo. Thanks for reporting it!
