### ISSUE TITLE
Installing NVM & NodeJS in a different directory....

### ISSUE THREAD

**Issue by brownsmart** [coreybutler/nvm-windows#180]
Hi on installation (Windows 10) I have changed the directory for both NVM and NodeJS however neither CMD or any other CLI i use (conemu, gitcli etc) does not seem to work, which is weird because the system environments are setup per the installation.

What is the best way of going about it?

**Comment by coreybutler** [comment]
Double check the `PATH` variable. There have been some reports that Windows 10 is automatically expanding the variables instead of keeping them as runtime variables. Bottom line is NVM4W is not being recognized in your `PATH`... so the question is what _is_ in your `PATH` (then we can figure out how it got there or lack thereof).

**Comment by coreybutler** [comment]
Closing due to age/response.
