### ISSUE TITLE
NVM use x.x.x 32 Error

### ISSUE THREAD

**Issue by rustyb** [coreybutler/nvm-windows#198]
Hi - Running into a small error on a Windows 7 machine.

Can install any version of node but when it comes to creating the link from ..\nodejs with `nvm use 6.3.1 32` to the version of node you wish to use it fails with a `fork/exec` error from elevate.cmd. See below:

<img width="526" alt="screen shot 2016-08-12 at 00 46 20 copy" src="https://cloud.githubusercontent.com/assets/53086/17607719/d34705d4-6027-11e6-9d49-3d38bd370863.png">

Any idea how to fix it? Have tried manually creating the link with:

`C:\Users\...\AppData\Roaming\nvm\elevate.cmd cmd /C mklink /D "C:\Program Files\nodejs" C:\Users\...\AppData\Roaming\nvm\v6.3.1` but that fails too.

**Comment by coreybutler** [comment]
Is this from a fresh install (i.e. the first time the command prompt was opened)?

**Comment by rustyb** [comment]
Hi @coreybutler sorry for the delay, this was post reboot after a fresh install.

**Comment by coreybutler** [comment]
@rustyb - dumb question.... `C:\.....\elevate.cmd` actually exists, right? I'm wondering if something got botched in the install. Perhaps the file never got copied to the proper location. If it's not there, you'll need the `elevate.cmd` and `elevate.vbs` from [here](https://github.com/coreybutler/nvm-windows/tree/master/bin).

**Comment by rustyb** [comment]
They definitely exist, but will try copy them over from the repo directly to see if that has any effect on it.

**Comment by coreybutler** [comment]
@rustyb - Are there any special characters or spaces in your username (i.e. the red part of your image)?

**Comment by hstadler** [comment]
Seems I had a similar problem on _Win 10 x64_ with _nvm 1.1.1_: My user home contains a space resulting in an error when running _nvm use_. The fix was to change the _root_ path in _settings.txt_ from

> C:\Users\User Name\AppData\Roaming\nvm

to

> C:\Users\USERNA~1\AppData\Roaming\nvm

**Comment by theblackhole** [comment]
I think found the solution : I had the same problem on my colleague's computer (Win10 x64 with nvm 1.1.1). His name is Léo so nvm was broken because of the special character "é" in his username.
I converted the _settings.txt_ file to UTF8 (without BOM) with notepad++ and it solved the problem ! 😄 
Maybe it would also solve the space issue...

**Comment by rustyb** [comment]
Hum I must actually go back and check that i'm 99% sure there actually was a space!

**Comment by korneliuskristianr** [comment]
Hi, maybe the problem is **because** windows username is using **space**  and **special character**.
To fix:
1. You change root path which doesn't any space using ```nvm root your_path``` and
2. **copy** file **elevate.cmd** and **elevate.vbs** ( download it from [here](https://github.com/coreybutler/nvm-windows/releases) ). 
3. After that install again your node version using ```nvm install 6.9.1``` ( whatever version  do you want)
4. Last, type ```nvm use 6.9.1 64``` (if your windows 64 bit)

**Comment by ctsstc** [comment]
I ended up just uninstalling everything with a fresh start. Then I used the installer and threw it in a path at the root of my drive for both nvm and nodejs.

**Comment by coreybutler** [comment]
spaces and encodings are supported in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8
