### ISSUE TITLE
unable to upgrade NPM version

### ISSUE THREAD

**Issue by mzvast** [coreybutler/nvm-windows#215]
I can't upgrade npm version.

### My Environment
- [x] Windows 10 x64 1607
- [x] My Windows installation is non-English.
- [x] nodejs 4 or 6

### reproduce steps

$ npm i -g npm
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "npm"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! path C:\Program Files\nodejs\npm
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\npm'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\npm']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Program Files\\nodejs\\npm' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EPERM: operation not permitted, lstat 'C:\Program Files\nodejs\npm'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EPERM: operation not permitted, lstat 'C:\Program Files\nodejs\npm']
npm ERR! error rolling back   errno: -4048,
npm ERR! error rolling back   code: 'EPERM',
npm ERR! error rolling back   syscall: 'lstat',
npm ERR! error rolling back   path: 'C:\\Program Files\\nodejs\\npm' }

**Comment by coreybutler** [comment]
You need to run this as admin or with a privileged user account.

`npm ERR! error rolling back Error: EPERM: operation not permitted, lstat 'C:\Program Files\nodejs\npm'` indicates your user account doesn't have permissions to do this.

**Comment by yvele** [comment]
@coreybutler @jagu-sayan All global installation must be done as admin? Or this is only related to npm?

**Comment by coreybutler** [comment]
@yvele - All global packages are subject to the same operating system conditions. It's all based on the choices made when installing NVM4W.

If the node directories are stored in a privileged directory, like `C:\Program Files` (as was the case for @mzvast), the operating system itself will restrict activity to admin users because `C:\Program Files` is a Windows protected directory. However; if the node directories are saved somewhere else, like `C:\Users\username\...`, the operating system doesn't require any special permissions and npm i -g any-module` will work without admin privileges.

**Comment by yvele** [comment]
@coreybutler Thanks for that clarification 😉  

But we installed a brand new Node version from scratch using NVM4W (with no previously node version installed).. and we expected to run `npm install -g`with no trouble.. hum..

Looks like `npm install -g` doesn't follow the symlink..

**Comment by coreybutler** [comment]
@yvele `npm install -g` **will** follow the symlink. In fact, there's no way for it not to because it's dependent on node. The important thing to remember is the `-g` flag writes to the `node_modules` directory within the _node installation root_, whereas a normal `npm install` installs the module to the _project_ root. In the case of global installations, the user must have permissions to write to the directory where node is installed, otherwise you'll see the permission errors from the OP.
