### ISSUE TITLE
NVM implicit dependency on Node for normal operation

### ISSUE THREAD

**Issue by bmcminn** [coreybutler/nvm-windows#230]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

Windows 7

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

`settings.txt`

### Expected Behavior

NVM to behave as designed.

### Actual Behavior

NVM is correctly installing and symlinking the node versions I request, however it is not persisting any configurations regarding `use` and `arch` commands.

![image](https://cloud.githubusercontent.com/assets/879984/20950661/a6297dd2-bbe6-11e6-9c41-b7423f959e4f.png)

### Steps to reproduce the problem:

Tried installing via the 1.1.1 installer, and this issue cropped up. Tried downloading and overwriting the files with the 1.1.1 no-install variant, same issue persists.

**Comment by bmcminn** [comment]
Alright, after some more digging, I learned that the NVM script isn't changing the filename of the downloaded node resource from `node64.exe` to `node.exe` within the given node version directory... not sure why that would be happening, but I'm guessing something within the version swap is hanging up, because it works fine now.

**Comment by bmcminn** [comment]
Just clarifying the points I made previously:

1. NVM wasn't supplying the correct node.exe reference in the symlinked directory provided by `settings.txt -> path`. The `node.exe` resource in question was a `~6Kb` file when the adjacent `node64.exe` was a `~20Kb` file, so I switched the filenames and everything worked correctly after that.
1. Digging into the NVM internals, the `node.go` script depends on a working Node.js instance in order to pull certain environment information that it utilzes. This places a strange dependency on Node being installed prior to installing/configuring NVM itself, which is not documented, nor suggested in the MSI utility.

If that didn't make sense, just let me know.

**Comment by coreybutler** [comment]
There is no _dependency_ on a pre-existing node installation. That is, in fact, one of the core tenants of this project. The `node.go` file contains methods for working with an active installation _if_ Node is available, but there are fallbacks when it does not exist. Basically, the `node.go` lib provides metadata to the utility, but no dependent functionality.

There was an edge case bug in switching architectures, which has been fixed in the master branch but has not shipped in a release yet (because I haven't had time yet). If you're compiling from source, you shouldn't run into this issue. Manually renaming the file, as you did, is what the utility is supposed to do for you... so I think you came across this issue and applied the manual fix (nice detective work, btw).

The subject of version management architecture is a hot one right now. There is an [active working group](https://github.com/nodejs/version-management) discussing architecture options, standards, workflow, etc.

**Comment by bmcminn** [comment]
Gotcha, I wasn't compiling from source when I encountered this problem, it was a completely fresh Win7 instance I was trying to bootstrap and happened to run into this problem.

I imagine it's possible I did run into the architecture switching bit you mentioned, however I wonder why it is that even when my `settings.txt` file contained the architecture I wanted, NVM refused to acknowledge that config? I may just not understand the nuances of the architecture switch error you mentioned without diving further into the issues tracker/internals of the utility, but it just seems strange to me that a fresh install would fail this mysteriously.

If anything, this may benefit from documentation in a Troubleshooting section of the `README.md`.

**Comment by coreybutler** [comment]
NVM4W should respect the `settings.txt` file, but Windows 7 doesn't consistently identify the architecture of an executable... which is why this utility is _technically_ only supported on Windows 8+ (see [the Windows 7 wiki](https://github.com/coreybutler/nvm-windows/wiki/Support-for-Windows-7-and-Earlier)). In other words, NVM4 windows will read the settings file to determine which version you want, and it will tell the OS. There seems to be a bug in the underlying OS functionality, which I'm hoping to resolve with newer versions of Golang.

That said, there are many users who have made this work on Windows 7, so I know it's possible. I don't have the resources to troubleshoot anything less than Win8 at the moment though. I do agree about putting something in the docs... I'll try to get something in there ASAP.

**Comment by coreybutler** [comment]
Closing due to age. Newer versions of NVM4W use newer versions of Go, which I believe resolved this.
