### ISSUE TITLE
Install version incompatible to nvm

### ISSUE THREAD

**Issue by ujaroe** [coreybutler/nvm-windows#247]
While "nvm install 7" or "nvm install 6.9" would install the latest available version of 7.*.* or 6.9.*, respectively, nvm-windows installs 7.0.0 or 6.9.0.

On the other hand I don't know how compatible nvm-windows should be. But at least the behaviour is somewhat unexpected to me.

**Comment by coreybutler** [comment]
nvm-windows is not trying to be nvm, so feature parity is not a priority. In fact, nvm-windows is much more aligned with the philosophies of n than it is with nvm. That said, I'm not opposed to the behavior nvm introduced (it has been requested before, which is why I'm closing this issue).

The version management group recognizes the confusion in the community and we've been discussing how all of these projects should coexist. It's still an open discussion. For my part, I intend to rename this project in the next major release to at least show a difference from nvm.

**Comment by ujaroe** [comment]
Thanks for the explanation. It's not too bad after fixing #246.

However, I still wonder how I could install or update to the latest available current/stable/lts version - which nvm supports as "special" versions. Is there any way to achieve this here as well?

**Comment by coreybutler** [comment]
It's reasonable to think about adding a few more keywords like `nvm install lts` or `nvm install current`. Again, I'm not really opposed to the behavior nvm introduced, so I could see adding that. I'd be open to a PR with that functionality if someone wants to add it. I'm not sure when I'll get around to it.
