### ISSUE TITLE
Feature Suggest Installation change

### ISSUE THREAD

**Issue by tracker1** [coreybutler/nvm-windows#254]
Instead of updating symbolic links for all users, globally...  What if you only updated part of the user's PATH environment variable to ensure than the nvm copy of node is first?

* Read PATH env arg
* Remove `%LocalAppData%/nvm/versions/...;` entries (may not be at the beginning any longer.
* Prefix selected version for the user.
* Prefix selected version's `./node_modules/bin`

Set the config to use subdirectories of the installed version for the node_modules and bin directories for globals.

Could this be done without elevated privileges?

**Comment by coreybutler** [comment]
Theoretically this could be done without administrative privileges at the user level (not system), but it is very risky. I tried doing this on Windows 8 with a `PATH` that had too many characters (thanks to a ton of Android SDK stuff). Rather than rolling back, it silently set the `PATH` to an empty string without triggering an error. This is something the installers can handle reasonably well, but I was unable to detect the error from Go. It didn't seem reliable enough, even though I love the idea of it.

The other consideration is user path modification will not immediately recognize the new version of node in different shells. If you run `nvm use x.x.x`, it would only modify the shell it's running in and any subsequent shells. This is similar to how the original nvm & nodist approach the matter, but the majority of feedback I received suggested system-wide modifications were preferred.

**Comment by tracker1** [comment]
Understandable.. via the UI, there is a USER and a SYSTEM environment variables area... not sure what it would take to fiddle there for the global, and also have it do the local env,  barring the very long path issue... weird.

The globals for the user are in the registry `//HKEY_CURRENT_USER/Environment` under the key `Path` .. that should work for the global setting...

For the local env, probably should do the [SetEnvironmentVariable  API call](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686206(v=vs.85).aspx) directly if you were calling `SET`, haven't looked at your code.

Man I really should just break down and take the time to get acquainted with go so I could help with this...

**Comment by coreybutler** [comment]
Accessing the registry requires elevated permissions, so keeping a global setting will always have that catch.

Go doesn't have direct access to the API, but `SET` could be called. Currently, the `mklink` utility is used to modify the symlink in [nvm.go:379](https://github.com/coreybutler/nvm-windows/blob/master/src/nvm.go#L379).

It sounds like the ultimate point is you'd like user-level control. 

I've tried hard to minimize interaction with environment variables and the registry, choosing instead to focus on common cross-OS patterns. The next version (which I'll be focusing on after the [Fenix](https://github.com/coreybutler/fenix) 3 release) will need to support macOS/Linux too, which has no registry. Go is pretty good at splitting up functionality by OS, so there are lots of implementation choices, but cross-platform consistency was one of the driving factors behind the choice to use symlinks.

I did do a little prototyping with hooks (like git) and am happy enough with the results that they're in the roadmap for the next version. For user-speciifc functionality, it would be possible to run a `pre` hook to switch a version for execution and immediately switch it back upon completion (among countless other possible customizations).

**Comment by tracker1** [comment]
Does even accessing the current user area require elevated permissions?

Basically, I'm wanting to potentially script usage, without having to click for permissions each time...  The way it is now is slightly more cumbersome to use with different versions in different projects.  Was hoping to see better alignment with the usage between this, and the original nvm shell scripts.

**Comment by coreybutler** [comment]
Elevated permissions are only required when running `nvm use` because all symlink operations in Windows require elevated admin permissions. Additionally, if you choose to use `C:\Program Files` to store your node installations, `nvm install` and `npm install -g` commands will require elevated permissions, because everything that writes to `C:\Program Files` requires elevated permissions. If you choose an alternative location, such as a user directory, this restriction does not apply. Basically, it has everything to do with whatever permissions the user defines on their file system. These statements are just based on the defaults most versions of Windows ship with. In other words, it's entirely dependent on the OS.

There are many ways to script permissions. The `runas` operation is one I'm sure you're already aware of. I have a tiny [elevation script](https://github.com/coreybutler/node-windows/blob/master/bin/elevate/elevate.vbs) that may help.

I have no intention of aligning with nvm's per-shell approach because, in my experience, it causes too many edge cases. In order to run _anything_ in a per-script manner, you must shim the executable. This modifies the operational context of the script, because it's just a wrapper. This is the source of most of the problems in [node-windows](https://github.com/coreybutler/node-windows), which shims node. There are other [use cases](https://github.com/nodejs/version-management/blob/master/edge_cases.md) behind the "pro simplicity" philosophy.

There are a few different [philosophies](https://github.com/nodejs/version-management/issues/4#issuecomment-258567834) for version management. The best _philosophical_ comparison I can make is:

- The closest Windows equivalent of `nvm` is `nodist`.
- The closest Windows equivalent of `n` is `nvm-windows`

The version management group is aware of the confusion around all of this, but we don't get to meet very often to discuss, so progress is slow. I am astutely aware that the name `nvm-windows` suggests an alignment with `nvm`.

The future of `nvm-windows` includes a name change to prevent confusion. It will also be cross-platform, focusing on a core of "pro simplicity". I intend to address "pro UX" principles as well, but it will likely be in a separate tool or add-on.... I haven't settled yet on the approach yet, but I fully intend to address the issues head-on. I already have some cross-platform support completed, but I won't be able to devote time to this until [Fenix 3](https://github.com/coreybutler/fenix) is released (in beta now, formal release target is May 1).
