### ISSUE TITLE
it does not install latest version like nvm does

### ISSUE THREAD

**Issue by eisbehr-** [coreybutler/nvm-windows#265]
Hello! :octocat: 

I want to talk about the handling of versions in `nvm-windows` in compare to `nvm` and `semver`. I know that you already talked about this, [like here](https://github.com/coreybutler/nvm-windows/issues/247). But I would like to bring this back to topic, because I think this is actually a pretty neat feature and would be nice for automated tasks too.

To be honest, I actually don't see a usecase for the current handling instead of the handling like `nvm` nad `semver` uses it.

I understand that you don't want toy copy the behavior of `nvm`, what always installs/ueses the latest possible version of a given `semver`.

For all who don't understand what I'm talking about. When using `nvm` (or things like `semver`) it will always use the latest possible version availbale:
```TEXT
$ nvm install 6    ->  will install node 6.10.3
$ nvm install 6.9  ->  will install node 6.9.5
$ nvm use 7        ->  will use node 7.10.0
$ nvm use 4.8.X    ->  will use node 4.8.3
```

What `nvm-windows` currently does is just to assume the lowest version available:
```TEXT
$ nvm install 6    ->  will install node 6.0.0
$ nvm install 6.9  ->  will install node 6.9.0
$ nvm use 7        ->  will use node 7.0.0
$ nvm use 4.8.X    ->  will use node 4.8.0
```

So, you don't want to implement that behavior. I don't know why you would like to have it this way, but I'm fine with this. But how about a new command parameter for the commands `install` and `use` to select the latest version?
```TEXT
$ nvm install 7 --latest
$ nvm use 7 --latest
```

```TEXT
$ nvm install latest 6
$ nvm use latest 6
```

```TEXT
$ nvm install -l 6
$ nvm use -l 4.3
```

With such commands, it is easily possible to create script and use a behavior like [travis](https://travis-ci.org) does in test runners (_which actually uses `nvm`_). This will remove a huge overhead to look for the latest version and put them manually in test cases and runners.

Thanks in advance! Looking forward to what you think about this ...

**Comment by coreybutler** [comment]
I am not opposed to this particular feature and there has been some progress towards it tracked in #214.

Just to clarify my position re: nvm, I'm not trying to keep NVM4W different for difference sake. It has some great ideas that clearly resonate with people. My stance is to separate opinionated workflow from non-opinionated workflow. This pretty much means anything that has to do with project-level or per-shell-level configurations. There is still value in project-level configurations, but it differs by user/opinion/need. I feel there are alternative ways to serve this need that are more flexible, which is what I'm working towards for the next major version (which is cross-platform).

Using the latest release of a particular major version falls into system level configuration, so I think it's a perfectly valid use case to add now. The only reason I haven't added it already is time constraints.

I'm going to close this since there are a few other related threads already open.
