### ISSUE TITLE
Error in switching the node version

### ISSUE THREAD

**Issue by brijeshrai** [coreybutler/nvm-windows#274]
I have downloaded nvm-windows v1.1.4 and installed it under "C:\Program Files\nvm-windows" directory on Windows 10.
I set the root directory to "C:\Program Files\NodeJS" by running the following command:` nvm root "C:\Program Files\NodeJS"`
After setting the root successfully, I installed node v6.10.3 and v7.10.0. Running `nvm list` command shows me both the versions.
When I ran command `nvm use 7.10.0`, I got following error:
_**exec: "C:\\Program Files\\NodeJS\\elevate.cmd": file does not exist:**_

I checked and found that elevated.cmd file is in "C:\Program Files\nvm-windows" directory, so I copied the file to "C:\Program Files\NodeJS" directory and ran the followind command again: `nvm use 7.10.0`, but got following error this time:
_**exit status 1: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.**_

**P.S.:** I had to set the root directory because **nvm-windows** was not considering the directory path given in `path` variable in **settings.txt** and was downloading node.js versions in the same directory in which **nvm-windows** is installed.

**Comment by coreybutler** [comment]
Setting the root will change the location where the node installation files are physically placed. This needs to be different from the symlink path. If you used the default for the symlink (c:\Program Files\NodeJS), then set the storage root to the same path, it will cause a conflict, resulting in exactly what you're experiencing.

To resolve this, set the root to any other directory.

**Comment by brijeshrai** [comment]
The reason why I had to change the root because nvm-windows is not following directory path given in symlink.
During installation, I gave installation folder path as "C:\Program Files\nvm-windows" and symlink path as "C:\Program Files\NodeJS". After installation values in settings.txt are:
_**root: C:\Program Files\nvm-windows
path: C:\Program Files\NodeJS**_
Problem is, when I installed node v7.10.0 by running the command` nvm install 7.10.0` node file gets downloaded and deployed in root directory "C:\Program Files\nvm-windows" and not in the symlink folder. 
I have checked that environment variable NVM_SYMLINK is pointing to directory "C:\Program Files\NodeJS".

**Comment by coreybutler** [comment]
This is all intended behavior, including installing node to the directory where nvm is installed by default. 

The symlink is modified every time `nvm use x.x.x` is run according to a simple pattern: `SYMLINK` ==> `INSTALLATION ROOT`

This means the symlink will point to the installation root, like:

`C:\Program Files\NodeJS` ==> `C:\Program Files\nvm-windows\v7.10.0`. 

Running `nvm install 6.10.3` and `nvm use 6.10.3` would change it to look like: 

`C:\Program Files\NodeJS` ==> `C:\Program Files\nvm-windows\v6.10.3`

However; when you the root directory was changed to `C:\Program Files\NodeJS`, the installation path was essentially being set to the same path as the symlink, effectively creating:

`C:\Program Files\NodeJS` ==> `C:\Program Files\NodeJS\v7.10.0`

A symlink cannot coexist as a link and directory simultaneously, which is why this is failing.
