### ISSUE TITLE
NVM not creating Symlink

### ISSUE THREAD

**Issue by 3to1null** [coreybutler/nvm-windows#277]
After installing the latest node version (8.0.0) via NVM and running  `nvm use 8.0.0` NVM is not creating a Symlink. When running `node` I get the error: `'node' is not recognized as an internal or external command, operable program or batch file.` I fixed this by adding the NVM root path to the Path variable, but this is not supposed to be necessary, right?

I did get an administrator pop-up upon running `nvm use 8.0.0`. There also was an error when running `nvm arch`, it displayed "Currently Configured: -Bit". `nvm list` however, did display everything correctly.

Since it is very easy to manually add 1 path to the Path variable, I don't think fixing this has have very high priority.

(Also, I might be able to help translate English to Dutch if you still need someone)

**Comment by coreybutler** [comment]
You're correct, this should not have been necessary. You already figured out the workaround. 

Could you provide details of your system? i.e. Win 7/8/10, language (I assume Dutch), etc.

The `-bit` issue happens on older versions of windows (because of OS bugs) and older versions of nvm4w (because of code bugs, fixed in newer releases), so make sure you have the latest release.

Thanks for the offer to translate. If you haven't already [signed up](https://coreybutler.typeform.com/to/ybqT6F), please do so. There have been a few submissions to help translate to Dutch, but I would actually like to have multiple people for each language to ease the burden on everyone.

I'm closing this since I _think_ it's a system-specific issue, but I'll reopen if that doesn't seem to be the case. Feel free to comment.
