### ISSUE TITLE
CTRL-C seems to stop the script but not the process?

### ISSUE THREAD

**Issue by moshmage** [coreybutler/nvm-windows#282]
I'm having a weird issue, which appeared only after I started using nvmw:
Whenever I use ctrl-c to stop the running script (on MINGW64 bash terminal) the NodeJS process is not killed. Using the normal windows terminal (win+r > cmd) everythin works fine.

### My Environment
- [x] Windows 10

### Expected Behavior

Script to stop and NodeJS process to get killed

### Actual Behavior

Script stops but NodeJS process lives on

**Comment by coreybutler** [comment]
I'm pretty certain this is a shell issue, not a nvm4w issue.

Also, just to make sure, you are using this project, right? [nvmw](https://github.com/hakobera/nvmw) is a different project.

**Comment by moshmage** [comment]
@coreybutler yep - I'm using this one;

It probably *is* a shell issue, I was just hoping it wasn't and that you may have had a similar problem.
Guess I'll have to use my google-fu, then :)

**Comment by coreybutler** [comment]
I typically stick to the normal shell because I used to run into countless issues with other shells that manipulate the OS in non-standard ways. Issue #58 isn't specifically related, but it did inspire a few comments from other users regarding different shells... maybe there are some insights there.
