### ISSUE TITLE
nvm install node

### ISSUE THREAD

**Issue by lxiaoixi** [coreybutler/nvm-windows#315]
Could not retrieve https://nodejs.org/dist/latest/SHASUMS256.txt.
Get https://nodejs.org/dist/latest/SHASUMS256.txt: net/http: TLS handshake timeout

Can you tell me how to solve it

**Comment by ankushgoyal27** [comment]
C:\WINDOWS\system32>nvm install 6.11.4 64

**Could not retrieve https://nodejs.org/dist/latest/SHASUMS256.txt.


Get https://nodejs.org/dist/latest/SHASUMS256.txt: dial tcp iPaddress:port: connectex: No connection could be made because the target machine actively refused it.**

Any suggestions.

Thanks,
Ankush

**Comment by nitrix-reloaded** [comment]
I too have the same issue persists in Windows 7.

**Comment by abhisdeshmukh** [comment]
Issue seems when working from behind office proxy. Set proxy before executing install command. 
C:\WINDOWS\system32> nvm proxy http://<proxy address>:<port>

**Comment by LuisaFernandaArango** [comment]
You must remove the proxy

**Comment by js2me** [comment]
It is not solving that problem but solving problem with installing nodejs via nvm. May be it can helped to someone.

Manual installation:
- Download your nodeJs version from mirror
- Open nvm folder (on Win10 it is `C:\Users\%USERNAME%\AppData\Roaming\nvm` )
- Create folder and name it like this `v{yourVersion}` ( Example: `v6.9.4` )
- Extract all files from folder which contains in downloaded acrhive into your folder from third step
![image](https://user-images.githubusercontent.com/16340911/51247160-52ba1f00-199d-11e9-8574-d1b544336f3b.png)

- Open command line and install node with your version using nvm ( Example: `nvm install 6.9.4` )
![image](https://user-images.githubusercontent.com/16340911/51247230-8eed7f80-199d-11e9-87e4-1a2da3fadc4b.png)

- And next step is set to use your node version `nvm use 6.9.4`
![image](https://user-images.githubusercontent.com/16340911/51247317-cceaa380-199d-11e9-9d66-ac840fd75339.png)

These steps are helped to me to install nodeJs ignoring company proxy

**Comment by coreybutler** [comment]
There's a chance this issue is occurring because the TLS/SSL certificate of the remote host expired, or it could have been issued by a distrusted CA that is no longer trusted (like certain Verisign CA's). This is a more common issue when using a public or private mirror, but it can happen when certificates are renewed too.

You can force NVM to bypass this using the `--insecure` flag, i.e. `nvm install 6.9.4 --insecure`:

![image](https://user-images.githubusercontent.com/770982/51366620-2a6d1600-1aac-11e9-9718-2df8bebe6df1.png)

**Comment by brrogers** [comment]
For my environment, all that is required is a system reboot. Then suddenly this is working again. Fails after a few days though. Curl and Google Chrome are both able to retrieve this file just fine when NVM has this issue. Seems like NVM could be caching the certificate and has issues after the site renews?

**Comment by vipra17** [comment]
For windows 10 nvm install 10.15.0 doesnt work. It gives the following error :
Get https://nodejs.org/dist/latest/SHASUMS256.txt: Parent proxy unreacheable
I tried setting nvm proxy but then it gives proxy authentication error.
Also I manually downloaded the version and placed it in C:\Users\xxx\AppData\Roaming\nvm\v10.15.0

**Comment by artyomilyin** [comment]
Can it be possible that you just forgot to enable nvm?
Try `nvm on`.

**Comment by coreybutler** [comment]
@vipra17 This sounds like an issue with your proxy. If you're getting a proxy authentication error, then something is either 

1. Misconfigured in your proxy address
1. You don't actually have access
1. The credentials aren't being passed to the proxy or the proxy is expecting them in a different form.*

*For that last point: NVM4W is not currently designed to handle anything other than basic auth (it's more of a function of the native HTTP client than NVM4W). Some proxies do not respect the `Authorization` header sent in an HTTP request. Instead, they expect the `Proxy-Authorization` header or a custom alternative. NVM4W doesn't support this at the moment. Since `Proxy-Authorization` is a standard HTTP header, I would like to add support, but it has been a low priority (requires a custom HTTP client within NVM4W). I do not really have a good understanding of how many people are actually using proxies which require this kind of authentication. So, it's on the roadmap, but currently sitting near the bottom of my priority list.

**Comment by goldtreefrog** [comment]
I didn't even need `nvm proxy none`, just `nvm off` and then `nvm on`, then the rest. (I don't believe I'm behind a proxy server.)

**Comment by coreybutler** [comment]
Closing due to age and the fact many new releases have been made since this was created. Please search other issues before creating a new one if your issues is not resolved.

**Comment by drewg2009** [comment]
> There's a chance this issue is occurring because the TLS/SSL certificate of the remote host expired, or it could have been issued by a distrusted CA that is no longer trusted (like certain Verisign CA's). This is a more common issue when using a public or private mirror, but it can happen when certificates are renewed too.
> 
> You can force NVM to bypass this using the `--insecure` flag, i.e. `nvm install 6.9.4 --insecure`:
> 
> ![image](https://user-images.githubusercontent.com/770982/51366620-2a6d1600-1aac-11e9-9718-2df8bebe6df1.png)

When I run this I still get the following error: 

C:\WINDOWS\system32>nvm install 16.13.0 --insecure

Could not retrieve https://nodejs.org/dist/latest/SHASUMS256.txt.


Get "https://nodejs.org/dist/latest/SHASUMS256.txt": dial tcp 104.20.23.46:443: i/o timeout

**Comment by radhika-lilly** [comment]
All above solution doesn't work for me. Can you please provide some other solution?

**Comment by Arthurficial-Intelligence** [comment]
I was able to solve this issue with proxy commands. This post helped me do it. 
https://stackoverflow.com/questions/50643043/unable-to-install-node-using-nvm-on-windows
clear instructions.

**Comment by JFishLover** [comment]
none of above are useful to me

**Comment by JFishLover** [comment]
您好！信件已收到

**Comment by Mahdi-Forghani** [comment]
Hi everyone

This worked for me in version `1.1.9`

1. Download your NodeJS version from https://nodejs.org/dist/

2. Extract it where you want

3. Open ```install.cmd``` at ```C:\Users\%USERNAME%\AppData\Roaming\nvm```

4. Enter the path where you extracted zip file

5. Enjoy 😘

**Comment by Chukwu3meka** [comment]
On windows I did like this:

found the file:C:\Users\...seu usuario ...\AppData\Roaming\nvm\settings.txt

and added the following line:  proxy: user:psw@host:port

**Comment by JFishLover** [comment]
您好！信件已收到

**Comment by tikhan1019** [comment]
> this works for me `nvm off` `nvm proxy none` `nvm on` `nvm install <node_version>` `nvm use <node_version>`

**Comment by JFishLover** [comment]
您好！信件已收到

**Comment by tikhan1019** [comment]
> this works for me `nvm off` `nvm proxy none` `nvm on` `nvm install <node_version>` `nvm use <node_version>`

Thanks. It works well.

**Comment by MartinhoMCM** [comment]
> Issue seems when working from behind office proxy. Set proxy before executing install command. C:\WINDOWS\system32> nvm proxy http://proxy address : port

it worked form me.

**Comment by JFishLover** [comment]
您好！信件已收到

**Comment by She1ry** [comment]
> this works for me `nvm off` `nvm proxy none` `nvm on` `nvm install <node_version>` `nvm use <node_version>`
It works now！thanks

**Comment by buyi-web** [comment]
修改nvm文件夹下的settings文件

**Comment by buyi-web** [comment]
node_mirror:npm.taobao.org/mirrors/node/
npm_mirror:npm.taobao.org/mirrors/npm/

**Comment by JFishLover** [comment]
您好！信件已收到

**Comment by greet-mamun** [comment]
> Can it be possible that you just forgot to enable nvm? Try `nvm on`.

This is the right answer. Thanks

**Comment by JFishLover** [comment]
您好！信件已收到
