### ISSUE TITLE
'npm link' issue with yeoman generator

### ISSUE THREAD

**Issue by gmarziou** [coreybutler/nvm-windows#33]
Hello,

I was trying to use latest version of [yeoman jhipster generator](https://github.com/jhipster/generator-jhipster), this implies to run 'npm link' in the generator source directory, everything seems to work fine (link has been created) but it fails when I try to use it.

It works well when not using nvm.

Here is how to reproduce the error with Node 0.10.35 on Windows 7 64bit

~~~~
git clone https://github.com/jhipster/generator-jhipster.git
cd generator-jhipster
npm link

npm install -g yo
yo jhipster
Error jhipster

You don't seem to have a generator with the name jhipster installed.
You can see available generators with npm search yeoman-generator and then insta
ll them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.
~~~~

**Comment by coreybutler** [comment]
This is not an NVM issue.

Since you've cloned jhipster instead of installing with npm, you also need to run `npm install` within the cloned directory. This is something npm does automatically, but cloning does not.

When I cloned the project and ran `npm install`, followed by `npm link`, the generator ran:

![image](https://cloud.githubusercontent.com/assets/770982/5666908/fbf5b5a8-9728-11e4-99bd-229a20030f06.png)

**Comment by gmarziou** [comment]
Thanks a lot and sorry for mis-reporting.

**Comment by gmarziou** [comment]
Your tool is great, especially because it does not require node or python to run as others do.

**Comment by coreybutler** [comment]
No worries, and I'm glad to hear you're finding it useful!!
