### ISSUE TITLE
Different versions in different console 

### ISSUE THREAD

**Issue by LovaBP** [coreybutler/nvm-windows#360]
### My Environment

- [X ] Windows 10

### I'm using NVM4W version:

- [ X] 1.1.5

### My issue is related to (check only those which apply):

- [ X] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

I'm using cmder.
In one console i want to use a v6 node version.
In another one i want to use a v8 node version.
But when i change a node version in to another console it's reflect to another, so both console have same node version

### Steps to reproduce the problem:
Open a console and go into (A). 
nvm use 6.11.1
Open another console and go into (B).
nvm use 8.11.1
Go to console (A)
nvm list and it's show that is selected 8.11.1

This don't depend on node version installed, you can test with two different node version

**Comment by b-dur** [comment]
This is actually not a bug. Unfortunately it is not possible to run multiple node version at the same time. This is due to the folder link function of the OS.

**Comment by coreybutler** [comment]
Actually, it's not just about symlinks, this was a distinct architectural choice. This sparked a conversation quite a long time ago, documented at https://github.com/nodejs/version-management/issues/4.

**Comment by rmechamatadobe** [comment]
In my opinion if this project ever wants Windows to compete with the MAC OS and Unix systems as a viable node development system; this issue should be addressed.  There is absolutely no technical reason you can't have multiple versions of node running at the same time in different consoles.  All you have to do is use different directories, create "symlinks" and manipulate the active PATH.  This is how MAC OS and Linux work.  

I recently switched back to Windows as a development system from the MAC and I'm completely blown away by how weak a development system Windows 10 has become.  

If you're creating a replacement/equivalent for some application/utility you should, at the very least, make it capable of doing what the original does; otherwise don't call it the same thing which sets the expectation that it can.

Right now my project requires that I run various versions of node on the same machine at the same time.  I'm currently using docker for windows to achieve this functionality but there are bugs in Docker for Windows that make using that solution cumbersome as well.  

I almost wish I would have went back to the MAC, but those machines cost twice as much for half the machine.  Today's technology is horrible.

**Comment by coreybutler** [comment]
Manipulating the active path is the exact reason why prior version managers for Windows had so many issues. Even the most minor corruption while setting the path can nuke the whole PATH variable. This is more prevalent on older versions of Windows, where there is a maximum character limit for the PATH variable. It is also significantly more challenging to modify the path in enterprise environments controlled by Active Directory, where elevated admin privileges are required. Symlinks only require admin permissions. 

The goal of this project was never to replace nvm or even be the equivalent. If you see other posts in old issues, you'll note that a) I regret the name choice and b) the next edition will not have nvm in the name at all. There are a tremendous number of edge cases that creep up in per-shell environments on Windows and it requires significant effort/time to support them all. I believe this is part of why Nodist's creator stepped away from the project. That said, the NVM4W roadmap is targeting a hook system, which would allow individual developers to mimic per-shell environments/workflows as they please, similar to git. I do not fundamentally agree that a version manager is the same as an environment manager, and this project focuses specifically on version management with the intention of providing developers the hooks they need to use the project the way they see fit.

If you really want the per-shell node environments, you could run the bash environment on Windows and use nvm, or you could use Nodist.

I can't say I've run into issues with Docker for Windows, so it would be nice to know what they are. I wrote a small utility (YMMV) for working with Node/Docker at https://github.com/coreybutler/workspace. I don't publicize it because it's kind of an internal tool, but perhaps it would help make Docker less cumbersome.

**Comment by rmechamatadobe** [comment]
@coreybutler Thank you Corey for the response.  It's always easier said than done and always easier to arm chair quarterback; than to get off my butt and contribute; that's for sure :).  

I've got a docker solution that works but you have to configure the javascript server to use the docker network interface address of 0.0.0.  

The "Linux on Windows" solution works fine except you have to keep two copies off everything, I.E. git. etc, and switch between consoles when you want to run Windows VS Linux programs; so there here are definitely other solutions.  

Thank you for telling me about the Nodist and your docker solution; I'm excited to check them out.  

Thank you for the explanation, response and direction.  I still love nvm for Windows but my MAC and Linux using co-workers always joke with me that I need to go back to the MAC :) so I'm always looking for ways to show that Windows is at least as good at being developer OS.

On a different topic the Docker for Windows issues I saw and reported on the Docker repo has to do with docker-compose and using specific container_name values in the YML file.  The gist of it is this, if you have a YAML file that uses an environment variable for the container_name and you run it in two shells that set that environment variable differently and then bring up one container and then try to bring up the other container the activation of the new container will shut down other running container.  This even happens if you aren't using environment variables and you use 2 yaml files that have hard coded container_names  being run from the same directory.  So this situation:
You a file, "1.yaml", that brings up container_name "a" and a "2.yaml" file that brings up container_name "b".   If you "docker-compose up -f 1.yaml" container a is created and is brought to life.
Then if you, while in the same directory, bring up container "b" by running "docker-compose up -f 2.yaml" it will for some reason recreate container "a" and as a result shut it down before it creates and brings up container "b".  If you the go back and "docker-compose up -f 1.yaml" it will recreate and kill container "b".  This only happens if you use the yaml files from the same directory.  Make a copy of the directory and you can run both containers at the same time just fine :).  This behavior doesn't seem to happen on Docker of MAC so I've reported this as an issue.
