### ISSUE TITLE
Feature request: ability to install npm separately from node

### ISSUE THREAD

**Issue by jakub-g** [coreybutler/nvm-windows#367]
I didn't find any mention about it in the docs or issues, and quickly checking the code, it seems that node and npm version installed are tightly coupled.

Sometimes however, you're stuck on a given major version of `node`, but would like to update `npm`. For example current node LTS is 8.11.3 which ships with npm 5.6.0, whereas the newest 5.x npm is 5.10.0.

Was this feature ever considered? I acknowledge that, with the way things are currently implemented, it might not be easy to get this right. For example
- say I installed `npm 5.9.0` when using `node 8.11.3`. Now when I `nvm use 10.0` (a different version of node), should the `npm` version change as well? (right now it does, as node-npm are tightly coupled)
- when I come back to `nvm use 8.11.3` which had a custom npm installed by me earlier, should I get that custom version of npm (`5.9.0`), or the one that I'd get on a clean install (`5.6.0`)?

As a first step, an easy solution could be implemented: drop the overridden version of npm when changing version of node (perhaps with a big fat warning). The next step could be to have a dictionary of node-npm versions used together, and that dictionary, when entry is non-empty, would take precedence over the automatic version of npm.

The only slightly tricky thing could be that after switching to newer node, you could get older npm if not careful.

One way to solve the potential issues could be perhaps to create a new "combo" command that would switch node and npm at the same time (more explicit hence less error-prone, but more tedious also for the users): `nvm use-combo node@8.11.3 npm@5.9.0`

**Comment by jakub-g** [comment]
As mentioned here https://github.com/coreybutler/nvm-windows/issues/294#issuecomment-349137801
`npm install -g npm@x.y.z` doesn't work when npm is installed via nvm

**Comment by coreybutler** [comment]
It's actually possible to install other versions of npm using the `npm install -g npm@x.x.x` syntax. NVM4W gets out of the way and delegates everything to node/npm, just as if the installation had occurred without NVM4W.

The problem here is npm. The v5.x.x release line has a major flaw where it will not remove itself, i.e. npm is hard-coded to prevent removal of specific files when not installed directly by the MSI. It actually affects most version managers to some degree.

Uncoupling npm from node would position the project directly between Node and npm's philosophies/roadmaps, which poses a conflict. I don't believe this project is the right place to manage this. NVM4W will stick as closely as possible to mirroring the exact same experience one would see if they installed Node directly.

That said, environment management has always been associated with version management, since version management is one of several elements of environment management. Due to the high demand for solutions in this domain, I've been experimenting with a separate (commercial) project focusing specifically on this problem domain. We have another product to launch before this would be released, but the current plan is to produce something and release it through my software firm, [Author.io](https://author.io).

I'm closing this since it veers off into a different subject matter, but feel free to comment.

**Comment by kplhub** [comment]
One way to upgrade npm only when using nvm:
1. In a new folder (somewhere): run "npm i npm", which will install a LOCAL npm copy. (If you read this comment you probably already know that "npm i -g npm" fails.)
2. Go to control panel > system > advanced system settings >environment variables, and, in the system variables list, edit the path variable by inserting a new path above the two lines with %NVM_...%, and let this new path point to "{Folder created in point 1.}\node_modules\.bin".

NB: This will override npm for all of the node versions controlled by nvm. So you should check that your new npm version is compatible with the node versions you are switching to by nvm. When using a very old node version for which the new npm is not compatible, you may temporalily inactivate the new npm version by temporalily rename the folder in point 1.
Howto know if npm is compatible with node?: Some hints here: https://blog.npmjs.org/post/165273023140/supported-nodejs-versions-in-the-npm-cli
Currently (2018-08-18) node 6 is in maintenance, so npm 6.4.0 (the current last version) should support node 6, 8, and 10. And, if I understand the link above correctly, npm 6 should continue to support node 6.
