### ISSUE TITLE
This project confuses me

### ISSUE THREAD

**Issue by David263** [coreybutler/nvm-windows#380]
I had just installed node.js and npm on my Windows computer, when the instructions (https://docs.npmjs.com/getting-started/installing-node) sent me here. Reading this README confused me totally. Do I need nvm-windows? Is it different from what I just installed?

I don't think I am interested in versions of anything; I just want to be able to download files using npm and try out whatever asynchronous programming I can do with node.js . Looking forward to a simple answer.

**Comment by libook** [comment]
No, this is not necessary.

This is an extra tool for managing node and npm versions more convenient on your Windows OS.

As we know that node and npm updates their versions frequently. And there is some people who working on many projects at one time with different versions of node. And in common, there must be only one version of node on your OS.
If you want to change the version of node at any time; or if you need multiple versions of node coexist. The nvm program is what you need. And this is the nvm for windows OS.

**Comment by coreybutler** [comment]
@libook is correct. I'm assigning this to myself because I think a blog post would help clarify this. Hopefully I'll find time for that soon.

**Comment by rageycomma** [comment]
Really hate to disagree, and I don't want to jump on a newbie, but isn't this just a case of not reading the documentation correctly? 

The page provided makes it pretty clear exactly what the difference is between installing node.js normally, and even why you would use nvm as opposed to install node locally. Also, it doesn't link here, it just mentions "a" NVM, not this one in particular. 

The getting started page says:
> If you just want to get started exploring npm, using the Node.js installation method is fastest. If you are an advanced developer ready to jump in and work with versions, use the node version manager.

Then further down it says:

> Install npm & manage npm versions
npm is written in Node.js, so you need to install Node.js in order to use npm. You can install npm via the Node.js website, or by installing a Node Version Manager or NVM. This chapter explains both options.

>If you just want to get started exploring npm, using the Node.js installation method is fastest. If you are an advanced developer ready to jump in and work with versions, use the node version manager. If you aren't sure, please read this chapter before you decide. You can always change how you run npm in the future.

When you then read the chapter it then goes on to explain:
> Since npm and node.js products are managed by different entities, updates and maintenance can become complex. Also, the Node.js installation process installs npm in a directory that only has local permissions. This can cause permissions errors when you attempt to run packages globally.

> To solve both these issues, many developers opt to use a node version manager, or nvm, to install npm. The version manager will avoid permissions errors, and will solve the complexities of updating Node.js and npm.

I think that's pretty clear, to be honest, no?
