### ISSUE TITLE
Unable to download legacy version 4.4.3 after installing nvm and linking it to latest node.js version

### ISSUE THREAD

**Issue by lapc506** [coreybutler/nvm-windows#385]
Hello @coreybutler is this part of the same issue [as this one](https://github.com/coreybutler/nvm-windows/issues/244)? I got a corporate user who needs me to install 4.4.3, the latest version was already installed and manually updated before installing nvm-windows. 
![image](https://user-images.githubusercontent.com/6913652/44813440-052c4980-ab97-11e8-9332-0f069925338c.png)

**Comment by coreybutler** [comment]
This issue is caused when your computer doesn't trust the remote resource SSL certificate. You can get around this using the `--insecure` flag, i.e. `nvm install 4.4.3 --insecure`. This is documented in the help - just type `nvm` to see it:

![image](https://user-images.githubusercontent.com/770982/44820745-d4104100-abb7-11e8-8d59-6bd3c9ecbc29.png)

**Comment by lapc506** [comment]
Hello Corey, on the screenshot I provided you can see I already used this option from the command prompt: `nvm install 4.4.3 --insecure` This is not the case either.

**Comment by coreybutler** [comment]
@lapc506 - I'm sorry, I didn't see that.

**Comment by coreybutler** [comment]
@lapc506 Are you using a proxy or behind a firewall? I can't recreate this.

![image](https://user-images.githubusercontent.com/770982/45198033-f6463680-b229-11e8-8126-cd72287dadf2.png)

**Comment by coreybutler** [comment]
Closing as stale.
