### ISSUE TITLE
NVM use failed - missing admin permission on MINGW

### ISSUE THREAD

**Issue by mauricioscotton** [coreybutler/nvm-windows#417]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [X] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [X] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior
Using NVM4W on CYGWIN(MINGW) fails to set NodeJS Version.
This bug is when you don't have Admin Permissions on Cigwin to set Node version.
I was able to use it using default windows CMD, that asked for admin permissions...
It is just to let you guys know about this bug! :D

### Actual Behavior
![image](https://user-images.githubusercontent.com/34411735/51171128-f923f880-18a7-11e9-9b82-0a16396e012e.png)

### Steps to reproduce the problem:
Use Cigwin(Mingw) without Admin Permissions
Run "_nvm use XX.XX.XX_"

**Comment by coreybutler** [comment]
Thanks for reporting this. I've added an entry to the [wiki](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#special-terminal-shells) and linked to this issue.

Bottom line, I'm not going to fix this, and that should be documented more clearly (thus the new wiki entry). There are too many special cases caused by non-standard shells (i.e. anything other than CMD and PowerShell). I initially experimented with this, but adding support for the nuances of each different version of each kind of shell is simply not sustainable for a solo developer. Instead, I've chosen to implement the standards, i.e. how Windows defines standard practice.
