### ISSUE TITLE
Problem installing node on windows for the first time using nvm windows.

### ISSUE THREAD

**Issue by martijnsenden** [coreybutler/nvm-windows#436]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [X] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [X] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

I installed nvm for windows on a citrix thin client with Windows Server 2012 R2. When I type `nvm` in the Git Bash terminal that I have installed, I get the nvm help menu. This should confirm that everything is working. When I now do: `nvm install latest all`, I get the following error message:
```
Could not retrieve  https://nodejs.org/dist/latest/SHASUMS256.txt.

Get https://nodejs.org/dist/latest/SHASUMS256.txt: dial tcp 104.20.23.46:443: i/o timeout
```

I also tried `nvm install latest all --insecure`, but that did not help.

### Actual Behavior

I would expect nvm to install the latest npm and node.

### Steps to reproduce the problem:

See steps in 'Expected Behavior'.

**Comment by netwiser** [comment]
please use nvm proxy your_proxy_and_port to setup the proxy for nvm

**Comment by coreybutler** [comment]
I don't think this is a proxy issue.

It looks like something is blocking your inbound connection at the network level. In this case, NVM4W is just the messenger. Older versions of Windows servers tend to have a pretty tightly locked down firewall, so I'd start by checking there. See if you can even access those  URL's from a browser on the server.

The other possibility is the Windows Certificate Trustchain doesn't recognize the TLS/SSL cert of the remote server. In this case, you can add `--insecure` to the end of the command to bypass the TLS/SSL validation step. I'm leaning more towards a firewall issue though, because TLS/SSL doesn't typically timeout when there is a problem. It normally says the remote host isn't trusted.

**Comment by martijnsenden** [comment]
Thanks. I had tried the --insecure option, so I guess the firewall is a
good bet.



Op do 18 apr. 2019 01:05 schreef Corey Butler <notifications@github.com>:

**Comment by terrycoughlan** [comment]
Not sure what's going on here but even when I try to install an older version of node via nvm - I continue to get this error: Could not retrieve https://nodejs.org/dist/**latest**/SHASUMS256.txt. shouldn't the url show the version of node i'm trying to install and not latest??
@coreybutler

**Comment by coreybutler** [comment]
@terrycoughlan The last line of the output identifies your specific problem. There is no internet connection. 

By default, the latest SHASUM is retrieved when NVM4W thinks it needs to retrieve the latest version (https://github.com/coreybutler/nvm-windows/blob/53bc08dfed5a1ec99a6d6fb8f4771f9de993b3de/src/nvm.go#L866). In your case, it does not recognized v14.20.1 as a version because you have no internet connection. It cannot retrieve the list of Node versions.
