### ISSUE TITLE
only available in 32bit bug.

### ISSUE THREAD

**Issue by rahulroy9202** [coreybutler/nvm-windows#44]
![only available in 32bit bug - nvm-windows](https://cloud.githubusercontent.com/assets/3462467/6459161/fce5ad02-c1b1-11e4-9125-25a7b4dbc7a9.png)

**Comment by vkbansal** [comment]
It's not a bug. You are typing wrong commands.

You must use
```
nvm install 0.10.32
```
and not 
```
nvm install 10.32
```

**Comment by rahulroy9202** [comment]
Hi. Sorry I didn't include any context in the bug report.

I meant to say that in case of such an error, it should say unrecognized version, instead of saying that the no existent version exists but only in 32bit. (my system is 64bit.).

**Comment by vkbansal** [comment]
@coreybutler might take a note about it

**Comment by coreybutler** [comment]
@rahulroy9202. I've merged your changes. While it may be a simple code change, I think this adds value to the overall user experience. Thanks for the PR!

**Comment by ublue1024** [comment]
![image](https://cloud.githubusercontent.com/assets/4499635/7059257/7c6d0510-dea0-11e4-9d0a-8e601f5d9b3c.png)

**Comment by ublue1024** [comment]
what's the prpblem here?

**Comment by coreybutler** [comment]
@ublue1024 - The error you're experiencing can be caused by one of two scenarios. First, if you're using an older version of Windows (like XP), it may be missing a native command. See issue #23 and #37 for details. 

The other cause is a small bug. If you don't install both the 32-bit and 64-bit versions of a specific node version, it can cause this behavior. The issue has been resolved in the master branch, but I have not and will not release this as a new version... only because my time is too consumed between my day projects and working on the next version of nvm-windows... which already has a fix for this (see the Gitter feed for more detail). In the interim, you can build from source. Another user wrote instructions in the wiki about how to do this.

**Comment by ublue1024** [comment]
Thanks,  my computer is running on Windows 7. I don't know how to build from source, so I prefer to wait for the next version.

**Comment by rainabba** [comment]
The 'v' prefixing really needs to be standardized. I was dealing with the same because of the inconsistency in prefixing versions with 'v'.
