### ISSUE TITLE
Command to install programmatically?

### ISSUE THREAD

**Issue by ORESoftware** [coreybutler/nvm-windows#444]
Looking at the readme, it's not obvious if there is a way to install programmatically. With NVM for *nix we can use curl

```
curl <some internet file> | bash
```

is there some way to install nvm-4-windows with the command line? I am looking to install on CICD servers programmatically.

**Comment by coreybutler** [comment]
There is a no-install method you could use (see releases for the download, or https://github.com/coreybutler/nvm-windows/wiki#manual-installation for instructions). However;  there is no executable _script_, primarily because on Windows you have to access the registry. So, you could use curl to download the manual installer, but you'd have to script the rest of it yourself.

Another option is there is a community maintained version on chocolatey, which might be easier.
