### ISSUE TITLE
"node.exe" instead of "node"

### ISSUE THREAD

**Issue by rm-rf-etc** [coreybutler/nvm-windows#477]
Why does node show up as `node.exe` instead of `node`? I'm running the ubuntu bash for Windows 10, and was able to install node with `nvm.exe install 11.11.0`, but node is only available from the command line as `node.exe`, even though npm is available as `npm`. Why is that? I guess the solution is `alias node=node.exe`?

**Comment by coreybutler** [comment]
The issue is running the Ubuntu bash environment is actually running the Linux kernel. It's no different than running a full blown Linux virtual machine. NVM4W is not designed for Linux, so this is expected behavior.

The "Linux kernel within Windows environment" is confusing. Bottom line, if you want to use the bash environment, run https://github.com/nvm-sh/nvm, which is designed for Linux.
