### ISSUE TITLE
Do you need PR review help and other help?

### ISSUE THREAD

**Issue by GeertVL** [coreybutler/nvm-windows#482]
It seems that there are a lot of PR's still open or not reviewed. Not a motivation to get contributions.
The latest release is from more than a year ago. 

Do you need any help?

ps.: sorry if I reached out via this way but I hope you are looking at this.

**Comment by coreybutler** [comment]
Yes, I do need help. 

I'm open to having additional maintainers. The biggest challenge is creating new releases, which has been a kludgy manual process to date. With the new Github actions supporting builds, I have been working on a means of automating the build and release process in a predictable and reliable manner.... there have been some hiccups during the Github action beta into GA release, but the process is gradually coming together. 

The most important areas where help is wanted are:

- **Reviewing, closing, and elevating issues.** There are alot of issues filed which are not related to NVM4W (such as npm issues, module problems, NVM for Linux, etc). There are also a whole bunch of duplicates filed. There really needs to be more moderation and I simply can't keep up (I maintain over 100 repos).
- **PR Review / Release Testing** - Hopefully this will be more streamlined.
- **Writing Guides**: While it doesn't seem like this would be necessary, I have helped alot of people on a 1:1 basis
- **Community Engagement People** (See note below)

The NVM for Windows community has grown substantially. There have been over 1.6M downloads, with a growth rate of roughly 60K/mo. My [patreon account](https://www.patreon.com/coreybutler) provides a whopping $9/mo with over half of that coming from a single donor, and the rest of it coming from patreons of [Fenix Web Server](https://preview.fenixwebserver.com). The point: there has been tremendous demand,  but very little in the way of support. While there are regular/recurring requests for new features, I've had to keep a slim and trim profile for this project because I simply can't support the project growth under these conditions. I would like to have some community feedback managers to collect and assess feedback, with the goal of identifying the biggest pain points. In other words, I need some ambassadors.

**Comment by GeertVL** [comment]
I want to help be being a maintainer/CEP. Free of charge (earn enough during my dayjob). 
I would suggest to give me the necessary access for a month or so and evaluate me afterwards. 

I suggest that I start dealing with the issues and the PR's. And I would help people 1:1 and if certain support issues come back regularly write a guide to point to. 

If I can help with anything else just give me a shout. 



Van: "Corey Butler" <notifications@github.com> 
Aan: "coreybutler/nvm-windows" <nvm-windows@noreply.github.com> 
Cc: "Geert Van Laethem" <geert.van.laethem@pandora.be>, "Author" <author@noreply.github.com> 
Verzonden: Maandag 18 november 2019 00:11:05 
Onderwerp: Re: [coreybutler/nvm-windows] Do you need PR review help and other help? (#482) 



Yes, I do need help. 

I'm open to having additional maintainers. The biggest challenge is creating new releases, which has been a kludgy manual process to date. With the new Github actions supporting builds, I have been working on a means of automating the build and release process in a predictable and reliable manner.... there have been some hiccups during the Github action beta into GA release, but the process is gradually coming together. 

The most important areas where help is wanted are: 

    * Reviewing, closing, and elevating issues. There are alot of issues filed which are not related to NVM4W (such as npm issues, module problems, NVM for Linux, etc). There are also a whole bunch of duplicates filed. There really needs to be more moderation and I simply can't keep up (I maintain over 100 repos). 
    * PR Review / Release Testing - Hopefully this will be more streamlined. 
    * Writing Guides : While it doesn't seem like this would be necessary, I have helped alot of people on a 1:1 basis 
    * Community Engagement People (See note below) 


The NVM for Windows community has grown substantially. There have been over 1.6M downloads, with a growth rate of roughly 60K/mo. My [ https://www.patreon.com/coreybutler | patreon account ] provides a whopping $9/mo with over half of that coming from a single donor, and the rest of it coming from patreons of [ https://preview.fenixwebserver.com/ | Fenix Web Server ] . The point: there has been tremendous demand, but very little in the way of support. While there are regular/recurring requests for new features, I've had to keep a slim and trim profile for this project because I simply can't support the project growth under these conditions. I would like to have some community feedback managers to collect and assess feedback, with the goal of identifying the biggest pain points. In other words, I need some ambassadors.

**Comment by coreybutler** [comment]
Thank you for the offer.

Let's start with reviewing/closing out issues. If you want to do code reviews on PR's, that too would be helpful and appreciated. However; I'd like to make sure that we connect on the PR's before anything gets merged or before you spend too much time on them. Right now, there are a few PR's that have added new features, which I'm not prepared to merge into the project until a standard is set. I'd like to focus on bug fixes, doc updates, etc. In other words, lets whittle down the backlog of bugs, then think about new features.

I'll email you so I can fill you in on some of the other details.

My point about Patreon wasn't really about money. I was trying to illustrate how the current support ratio is 1:1.5M and how my time (like most) is primarily consumed with my paid work.... so it's really more like 0.25 people for every 1.5M users :-) 

In the past, I've offered to run some additional services to help make this project better, such as autoupdate services, signed releases, a translation service (over 400 people offered to translate), etc. Many of those platforms cost quite a bit.... that's been changing recently and I try to keep an eye on those things, but I just haven't had time to set that kind of stuff up yet.

I'll be in touch via email soon. I'm going to leave this thread open in case there are others who are interested in helping as well.

**Comment by memark** [comment]
@coreybutler @GeertVL Hi guys! How did this work out? Are you still choked with work?

I've been thinking about contributing to this project, but feel a bit discouraged by the large number of PRs waiting. Would my work be looked at in reasonable time? (Or should I just fork?)

**Comment by mark-stopka** [comment]
@memark, same here, @coreybutler would it help if I automate the release process with GitHub Actions?

**Comment by coreybutler** [comment]
I'm closing this for now. I could still use help, primarily with responding to issues though, so feel free to reach out. There are _many_ duplicate issues filed and a lot of people who need help understanding how Node installations impact their system. I do what I can to keep the wiki updated and answer questions, but it is overwhelming. I am trying to wind down efforts on NVM4W so I can focus my attention on rt, the successor project (described in the Github Discussion "welcome" thread).
