### ISSUE TITLE
cmd don't identify "nvm use..."

### ISSUE THREAD

**Issue by pedro8742** [coreybutler/nvm-windows#528]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

1.1.7

### Expected Behavior

nvm use 12.16.2 

### Actual Behavior

exit status 1: 'C: \ Users \ Pedro' is not recognized as an internal command
or external, an operable program or a batch file.

### Steps to reproduce the problem:
open cmd as adm

nvm install 12.16.2

nvm use 12.16.2

**Comment by carlobolla** [comment]
This is definitely due to a space in the path to node. Having the same issue as well

**Comment by coreybutler** [comment]
If the path is _actually_ `C: \ Users \ Pedro` instead of `C:\Users\Pedro`, then something was likely entered incorrectly during installation. NVM4W will not inject spaces (or any other characters) into the path. So, this may be a simple copy/paste error. If there actually is a space in the username, such as `C:\Users\Pedro Surname`, then the link @carlobolla pointed out is accurate.

Closing as a duplicate.
