### ISSUE TITLE
while using nvm v11.0.0  i m geting this error   fork/exec C:\Users\sakshi\AppData\Roaming\nvm\elevate.cmd: The system cannot find the file specified.:

### ISSUE THREAD

**Issue by sakshi8271** [coreybutler/nvm-windows#537]
Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

Run `nvm version` if you don't know.

### I have already...

- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by Tascano** [comment]
Hey Sakshi, Did you get any solution to this? 
I am facing the same issue.

**Comment by Dolers** [comment]
For me it happened when nvm install path and the path where the node have been downloaded by nvm, are not the same.
To workaround this, simply copy the elevate.cmd and  elevate.vbs next to that node version folder.

**Comment by letsgo0** [comment]
I met the same problem.

My nvm  and node downloaded looks like in the same path.

I have been troubled in this problem. No solutions can be found for me. It seems nvm4w dosen't updates for a long time. Should  I use another node version manager?

**Comment by coreybutler** [comment]
Check the file path. If the file doesn't exist, you can download them from https://github.com/coreybutler/nvm-windows/tree/master/bin.

More times than not, this occurs because people a) ignore the README by failing to uninstall previous versions of Node or b) not installing with administrative privileges. Failing to uninstall old versions can impact the PATH variable, while failing to install with administrative privileges means Windows will prevent the action.

**Comment by mahede182** [comment]
### Solution
One possible solution to this issue is to run the `sfc /scannow` command in the Command Prompt with administrative privileges. The SFC (System File Checker) command checks for corrupted system files and repairs them if necessary. Here's how to do it:

Open the Command Prompt as an administrator. To do this, right-click on the Start menu and select "Command Prompt (Admin)".
Type the following command and press Enter:` sfc /scannow`
Wait for the scan to complete, which can take some time. If any corrupted files are found, the SFC command will automatically repair them.
Restart your computer and try installing NVM again.
Note that this solution may not work for everyone, as the underlying cause of the error can vary. If the problem persists, there may be other steps that you can take, such as checking your antivirus software settings or performing a clean boot of your system.

I hope this helps! Let me know if you have any questions.
