### ISSUE TITLE
nvm use <version> shows error even after proper installation

### ISSUE THREAD

**Issue by ArkapravaNandy** [coreybutler/nvm-windows#538]
Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [*] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

Run `nvm version` if you don't know.

### I have already...

- [ *] read the README to be aware of npm gotchas & antivirus issues.
- [ *] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ *] verified I'm using an account with administrative privileges.
- [ *] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ *] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ *] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by cpoptic** [comment]
Also having this issue.
Windows 10, 64-bit

`nvm -v`
> Running version 1.1.7.

I've already installed version `14.3.0`

'nvm list`
> 14.3.0

but when I run `nvm use 14.3.0`
I get this error:
> exit status 1: The system cannot find the path specified.

I strongly suspect it's due to that PATH variable, so running  `path` from CMD line shows that the PATH includes   `;C:\Users\<user>\AppData\Roaming\nvm;C:\Program Files\nodejs`

Also, checking the System environment variables shows these two stored under different path variable names, so I'm assuming nvm is just concatenating them to the end of the path:

`NVM_HOME`  `C:\Users\<user>\AppData\Roaming\nvm`
`NVM_SYMLINK`  `C:\Program Files\nodejs`

Going out of my mind trying to figure this out.  Any suggestions?  My instinct is to manually modify the Path system environment variable, as I think it's left over from a previous install/uninstall of NVM4W

**Comment by coreybutler** [comment]
Spaces are now supported in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8
