### ISSUE TITLE
problem after npm install

### ISSUE THREAD

**Issue by FinnsonLiu** [coreybutler/nvm-windows#562]
Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 10

### I'm using NVM4W version:

Run `nvm version` if you don't know.

### I have already...

- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

At first it's a problem listed, but i'm having python 3.7 instead of python 2.7.x , and my environment path is correct. 
![first](https://user-images.githubusercontent.com/69029822/91199212-9291ce00-e6cb-11ea-9fb9-27251aabc0df.png)

This is the problem I faced after the path was setted

![second](https://user-images.githubusercontent.com/69029822/91199248-a0475380-e6cb-11ea-8cf9-ab3f17a22e4a.png)

**Comment by coreybutler** [comment]
This is an npm issue, not NVM4W. NVM4W doesn't touch npm. I'll be closing the issue.

In an effort to not leave you stranded, here are a few thoughts to experiment with. First, double checking the path. You may need to escape the backslashes. I'm not don't recall how `npm config` handles paths, but you may need to do `C:\\Users\\surface\\....` since a backslash is typically escaped by JavaScript.

The error says you can set the PYTHON _environment_ variable. That's not something you do with npm. You would do that in one of these ways:

`set PYTHON "C:\Users\surface\AppData\Local\Programs\Python\Python37"`
`setx PYTHON "C:\Users\surface\AppData\Local\Programs\Python\Python37"`
`PYTHON "C:\Users\surface\AppData\Local\Programs\Python\Python37" node myscript.js` (at runtime)

Clearly you're trying to install a native module. It could be a missing a native dependency. If you suspect that, consult the project owner of the package you're trying to install.
