### ISSUE TITLE
 The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by qq1209974887** [coreybutler/nvm-windows#580]
**Environment：** Windows10 operating system

**Quesion:**  npm download failed, Rolling Back, Rollback failed. Remove npm-v3.10.10.zip: The process cannot access the file because it is being used by another process.

![image](https://user-images.githubusercontent.com/18743063/98446950-3b44bb00-215c-11eb-86a4-42724f82f96e.png)

**Tried solutions:** Computer shutdown and restart, still not solve the problem, is still the same error.

**Comment by coreybutler** [comment]
Cannot recreate:

![image](https://user-images.githubusercontent.com/770982/98451629-24c34300-210d-11eb-9e39-2056d9f96a36.png)

**Things to look for**
1. Make sure you've uninstalled any prior versions of Node that were installed _without_ NVM4W. Same goes for npm.
1. Make sure a firewall isn't blocking the download.
1. Make sure your user has the appropriate permissions (this is unlikely to be the problem in this particular case, since you can get a partial file)

This is most commonly caused by a network failure. You can also download npm and install it manually if needed.

**Comment by mhscott64** [comment]
We see this frequently in our shop.  The message is generated in web.go->func  Download(...).  The top of this function contains:

     output, err := os.Create(target)
     if err != nil {
       fmt.Println("Error while creating", target, "-", err)
     }
     **defer output.Close()**
    ...
    **  defer response.Body.Close()**

Later, there are 2 different error handling stanzas.  The one for ctrl-c includes:

		output.Close()
		response.Body.Close()
The one for an HTTP failure does not include these closes.  So, in the event of an HTTP failure, the code attempts to delete the folder containing the failed download, but cannot because the output file is still open.  This results in the "rollback failed" message.  

If this analysis is correct, one solution would be to add the closes that are found in the ctrl-c handler to the http error handler.

**Comment by lfl976** [comment]
I modify the nvm mirror(npm&node) and  met the same issues，delete the mirror saved the problem.

**Comment by gregovin** [comment]
The issue is still present on v1.1.9, I just tried to use nvm install 13.7.0 and cannot use that version

**Comment by drewg2009** [comment]
Same I am also getting this issue: 


```
C:\WINDOWS\system32>nvm install 16.13.0Downloading node.js version 16.13.0 (64-bit)... CompleteCreating C:\Users\n0311764\AppData\Roaming\nvm\temp Downloading npm version 8.1.0... Download failed. Rolling Back.Rollback failed. remove C:\Users\n0311764\AppData\Roaming\nvm\temp\npm-v8.1.0.zip: The process cannot access the file because it is being used by another process.Could not download npm for node v16.13.0.Please visit https://github.com/npm/npm/releases/tag/v8.1.0 to download npm.It should be extracted to C:\Users\n0311764\AppData\Roaming\nvm\v16.13.0
--
```

**Comment by tomgcavanaugh** [comment]
Turn on "Developer Mode" by searching for the developer settings.

**Comment by drewg2009** [comment]
> Turn on "Developer Mode" by searching for the developer settings.

Developer settings for NVM?

**Comment by coreybutler** [comment]
Developer Mode is part of Windows. See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145

![image](https://user-images.githubusercontent.com/770982/167864297-6372fb36-09b4-421e-ac94-a2cbdfe44d9c.png)

**Comment by nicolasguzca** [comment]
> Developer Mode is part of Windows. See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145
> 
> ![image](https://user-images.githubusercontent.com/770982/167864297-6372fb36-09b4-421e-ac94-a2cbdfe44d9c.png)

This worked perfectly,  thanks

**Comment by Srutututu** [comment]
I get this error only if trying to install node 14.19.2
I can install 10.23.0 and 12.23.0 without issues and use them.
Maybe this can help identify the cause?

**Comment by johnvt** [comment]
> I get this error only if trying to install node 14.19.2 I can install 10.23.0 and 12.23.0 without issues and use them. Maybe this can help identify the cause?

Confirmed. I could even install 14.9.1 (npm 6.14.16) without problems, while 14.9.2 (npm 6.14.17) gives "download failed".

**Comment by Juuldamen** [comment]
I see the same behaviour as @johnvt. Older versions such as `14.17.5` and `14.9.1` work just fine. But `14.19.2` doesn't. Toggling the developer mode setting on or off doesn't seem to matter.

The command is ran in an elevated Git Bash Windows Terminal instance.
```bash
$ nvm install 14.19.2
Downloading node.js version 14.19.2 (64-bit)...
Complete
Downloading npm version 6.14.17... Download failed. Rolling Back.
Rollback failed. remove C:\Users\xxxxx\AppData\Roaming\nvm\temp\npm-v6.14.17.zip: The process cannot access the file because it is being used by another process.
Could not download npm for node v14.19.2.
Please visit https://github.com/npm/cli/releases/tag/v6.14.17 to download npm.
It should be extracted to C:\Users\xxxxx\AppData\Roaming\nvm\v14.19.2
```

```bash
$ nvm version
1.1.9
```

Output of winver
![image](https://user-images.githubusercontent.com/31408341/168764872-ce2106ce-4234-4e16-873d-9c43f7820c49.png)

**Comment by joshtransient** [comment]
Can also confirm this happens for 14.19.3 for me.

**Comment by xiaoyang678** [comment]
nodejs 14.19.3，14.19.2 is failed.

**Comment by xiaoyang678** [comment]
https://github.com/coreybutler/nvm-windows/issues/373#issuecomment-529991743

https://github.com/npm/cli/issues/4890

The above helped me, but the specific reason is still unknown, maybe npm official problem

**Comment by maddyjolly2112** [comment]
I have the same problem, it only installs which `nvm list available `shows in the list, rest fails.
