### ISSUE TITLE
Not recognized as an internal or external command after `npm link`

### ISSUE THREAD

**Issue by DasdWaller** [coreybutler/nvm-windows#587]
OS: Windows 10 (latest version)
NVM: latest version
NodeJS: 15.2.0
NPM: 7.0.8

I use `npm link` in my project. When I use the command to run the project, show an error :
`'cli-example' is not recognized as an internal or external command,
operable program or batch file.`
This problem have faced it for first time.
I use this example [code](https://github.com/dkundel/create-project)

**Comment by coreybutler** [comment]
I don't think NVM4W is causing this, otherwise you wouldn't get that error. If it were an NVM4W issue, you wouldn't even be able to run `npm link`.

Does your code include the shebang that's required on CLI utilities, such as [this](https://github.com/dkundel/create-project/blob/master/bin/create-project#L1)? That's usually why CLI tools aren't recognized.

**Comment by DasdWaller** [comment]
Thanks for the reply @coreybutler.
I just clone the repo and run `npm link` and then error. I think clearly and I think the problem is from Windows. I'm not sure, but i think the problem is from windows not from nvm. Is the right the [environments variables](https://prnt.sc/vl0imr)?
