### ISSUE TITLE
[Build Tools] Please update to a version compatible with Windows 10 20H2.

### ISSUE THREAD

**Issue by Vixb1122** [coreybutler/nvm-windows#589]
### My Environment

Windows 10 20H2.

### Expected Behavior

built success.

### Actual Behavior

built failure 
zip.exe and iscc.exe(inno-setup) don't compatible with system.

### Steps to reproduce the problem:

1. update windows to 20H2
2. clone repo
3. go get deps
4. run '.\build.bat'

**Comment by TheSpartaPT** [comment]
This #386 used to be a working fix, but somehow I'm not being able to build it properly now, build.bat runs fine until the end when it throws this error: `Could Not Find C:\nvm-windows-master\bin\nvm.exe` and the built binaries are missing the nvm.exe too, so you can build it and install it but it's kind of useless because the file doesn't exist

**Comment by coreybutler** [comment]
The build tools have been updated in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8
