### ISSUE TITLE
NPM not recognized in Powershell or Command Prompt

### ISSUE THREAD

**Issue by bleepzter** [coreybutler/nvm-windows#612]
### My Environment

- Windows 10 Pro

I noticed that NVM installed in:
C:\Users\[user]\AppData\Roaming\nvm\

It created a symbolic link in "C:\Program Files\nodejs\" pointing to:
C:\Users\[user]\AppData\Roaming\nvm\v15.8.0

It also created the following system environment variables:
NVM_HOME: C:\Users\[user]\AppData\Roaming\nvm\
NVM_SYMLINK: C:\Program Files\nodejs\

and the following user environment variables:
NVM_HOME: C:\Users\[user]\AppData\Roaming\nvm\
NVM_SYMLINK: C:\Program Files\nodejs\

The path system and user environment variable includes both:
%NVM_HOME%
%NVM_SYMLINK%

### Expected Behavior

npm install -g angular@latest should work.

### Actual Behavior

node --version works and returns the correct version number. However NPM does not.

![image](https://user-images.githubusercontent.com/3333921/107137334-7b811a00-68c0-11eb-8d85-834140f09f44.png)

![image](https://user-images.githubusercontent.com/3333921/107137205-fb0de980-68be-11eb-92b7-5656c1e879c4.png)

### Steps to reproduce the problem:

Download the installer for windows. (1.1.7)
Run the installer.
Install Node v15.8.0

![image](https://user-images.githubusercontent.com/3333921/107137225-40321b80-68bf-11eb-9a49-e36c1d4b5b37.png)

**Comment by TiKevin83** [comment]
probably related to #606

**Comment by shorstki** [comment]
It's probably more like each node version installed with nvm have separate npm and changing version in NVM is not changing path to right npm. And also each node has separate node-modules, so packages installed with different node and npm are in different locations `NVM_HOME/node version/node-modules`

**Comment by coreybutler** [comment]
@shorstki is correct. There is a different installation directory for each version of node and its modules. Global npm modules must be reinstalled for each version, since each version is treated separately.

There are other reasons npm may not be recognized. Spaces in path names/install roots were a challenge in v1.1.7, but have been resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8. Lacking permissions can also cause this when using a protected directory (like `C:\Program Files`).

I'm closing this because I believe the technical issues have been resolved in v1.1.8. It is important to understand that each version of Node is treated as an independent installation though. Managing the npm environment is not in the scope of this project, but it is being considered in rt (the successor project I'm working on - see the "welcome" thread in the Github discussions for details).

**Comment by aahmedfaraz** [comment]
This is because it is powershell, try command prompt (administrator)

**Comment by coreybutler** [comment]
@aahmedfaraz no - this is not due to the shell. NVM4W is supported in both PowerShell and the standard command prompt.

**Comment by boualikamel** [comment]
> @shorstki is correct. There is a different installation directory for each version of node and its modules. Global npm modules must be reinstalled for each version, since each version is treated separately.
> 
> There are other reasons npm may not be recognized. Spaces in path names/install roots were a challenge in v1.1.7, but have been resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8. Lacking permissions can also cause this when using a protected directory (like `C:\Program Files`).
> 
> I'm closing this because I believe the technical issues have been resolved in v1.1.8. It is important to understand that each version of Node is treated as an independent installation though. Managing the npm environment is not in the scope of this project, but it is being considered in rt (the successor project I'm working on - see the "welcome" thread in the Github discussions for details).

unfortunately it's not working in new version.
