### ISSUE TITLE
Cannot set node version on Win 10 Pro x64 - and cannot set arch version

### ISSUE THREAD

**Issue by hardysabs2** [coreybutler/nvm-windows#645]
Installed from latest setup exe

PS C:\> nvm version
1.1.7

Windows 7 Pro x64

I am trying these commands to set the node version.

PS C:\> nvm arch
System Default: 64-bit.
Currently Configured: -bit.
PS C:\>
PS C:\>
PS C:\>
PS C:\> nvm list

    14.17.1
PS C:\> nvm use 14.17.1
Now using node v14.17.1 (64-bit)
PS C:\> node -v
& : The term 'C:\Users\ahardy\AppData\Roaming\npm/node_modules/node/bin/node' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\Users\ahardy\AppData\Roaming\npm\node.ps1:10 char:3
+ & "$basedir/node_modules/node/bin/node"   $args
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ahardy...s/node/bin/node:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Expected behaviour is for the node version to change
I have also tried

nvm use 14.17.1 64
nvm use 14.17.1 x64
nvm use 14.17.1 64bit
nvm use 14.17.1 64-bit

No difference.

I have tried 
nvm off
nvm on

I have closed and opened a new powershell

It's not in the nvm command help but I have also tried
PS C:\> nvm arch 64
Default architecture set to 64-bit.
PS C:\> nvm arch
System Default: 64-bit.
Currently Configured: -bit.
PS C:\> 

then all of the above again

I think it has something to do with the arch version but I don't know how to fix it.
Thanks

**Comment by konrado-zooplus** [comment]
Hi,
I faced the same issue.

But fortunately we have "Admin by request" installed which raised an alert when I tried to switch to some other node instance: File {my current directory}\cmd.exe does not exist.
So that was a clue for me that sth is looking for cmd.exe in the path that I was in. When I run the same commands (nvm use X.Y.Z) from cmd opened with Administrator rights - the alert did not show up (so some exception must be swallowed somewhere underneath).

Based on that I went to path: C:\Windows\system32 (where cmd.exe resides in) and run the command 'nvm use X.Y.Z' - now it worked properly as the cmd.exe was in the path.

I did not do any further investigation but I hope that what I described may be used both as a workaround (for now) and as a clue for finding the bug by the maintainers.

**Comment by hardysabs2** [comment]
Received an issue reply in email but I cannot see the reply in the github
page when I visit it via the email "view it on GitHub" link for some reason.

I am not sure I follow the explanation.

Is there a step by step I can follow to solve this?

Thanks,

Andrew

**Comment by gundik** [comment]
Hi,
I faced the same issue.

But fortunately we have "Admin by request" installed which raised an alert when I tried to switch to some other node instance: File {my current directory}\cmd.exe does not exist.
So that was a clue for me that sth is looking for cmd.exe in the path that I was in. When I run the same commands (nvm use X.Y.Z) from cmd opened with Administrator rights - the alert did not show up (so some exception must be swallowed somewhere underneath).

Based on that I went to path: C:\Windows\system32 (where cmd.exe resides in) and run the command 'nvm use X.Y.Z' - now it worked properly as the cmd.exe was in the path.

I did not do any further investigation but I hope that what I described may be used both as a workaround (for now) and as a clue for finding the bug by the maintainers.

**Comment by hardysabs2** [comment]
I am not sure I follow the explanation.

Is there a step by step I can follow to solve this?

Thanks,

**Comment by gundik** [comment]
It's not a solution but rather a workaround:
1. open console
2. go to `C:\Windows\system32`
3. change the node version as desired: `nvm use 14.17.1`
4. should work

**Comment by hardysabs2** [comment]
Cool - thanks I'll give it a try later

**Comment by hardysabs2** [comment]
I don't need to use any of these then?

nvm use 14.17.1 64
nvm use 14.17.1 x64
nvm use 14.17.1 64bit
nvm use 14.17.1 64-bit

Or

It's not in the nvm command help but I have also tried
PS C:> nvm arch 64
Default architecture set to 64-bit.
PS C:> nvm arch
System Default: 64-bit.
Currently Configured: -bit.
PS C:>

Discussed above

**Comment by coreybutler** [comment]
Closing due to age. Since this issue was filed, a new version has been released: [v1.1.9](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9). If the issue persists, please open a new issue for v1.1.9.
