### ISSUE TITLE
Powershell 7.1, nvm use followed by node invocation in script errors

### ISSUE THREAD

**Issue by EzraM** [coreybutler/nvm-windows#650]
**NVM4W version:** 1.1.7

### My Environment
- Windows 10
- Powershell 7.1.3

### Expected Behavior
Powershell 7 script:
```powershell
nvm use 14.16.1
& node.exe -v
& node.exe -v
```
Expect to see node version printed twice.

### Actual Behavior
Following output after running the script:
```
Now using node v14.16.1 (64-bit)
&: C:\...\minimal-case.ps1:2
Line |
   2 |  & node.exe -v
     |    ~~~~~~~~
     | The term 'node.exe' is not recognized as a name of a cmdlet, function, script file, or executable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.

v14.16.1
```

### Steps to reproduce the problem:
Save the Powershell script to file and run in Powershell 7.1.3.

### Note
Running a Get-Command before attempting the command runs without an error.
It seems like act of looking to resolve the command makes it so the command then runs on the first try.
```powershell
nvm use 14.16.1
Get-Command -all node
& node.exe -v
```

My guess is the bug is in Powershell 7 somewhere, but not sure how to narrow down the issue to that layer.
We changed our scripts to include the following so they run without errors.
```powershell
Get-Command -all node >> null
```

**Comment by siada** [comment]
I ran into this issue when using nvm in a CI environment, it's due to the nvm escalates privileges to be able to swap the symlink....

This take a very small period of time that runs _outside_ the nvm exe, so the call to "nvm use" completes and in the background it will switch versions but by which point your call to node has tried to call the node.exe that doesn't exist

The fix we used in our CI environment was to `start-sleep -seconds 5` kinda stupid really...

**Comment by scottnonnenberg-signal** [comment]
Yes, this should be documented. Just ran into this in a build process. It's important to `sleep` after running `nvm use <version>` in a script that will immediately do something with `npm`.

**Comment by coreybutler** [comment]
The only possible fix for this is to delay the completion of the nvm executable, i.e. sleeping or waiting for a loop to check whether the version is found. For most users, this will add latency to the `use` process. I'm not prepared to do that at this time since it could impact several million people. I have this listed as an item to address in rt (successor project).

In the meantime, I agree with @scottnonnenberg-signal that this should be documented... so I've added a note to the [wiki](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#delayed-changes).
