### ISSUE TITLE
Getting error "exit status -1073741819:" (Golang ERROR_ACCESS_DENIED?) when trying to set nodejs version

### ISSUE THREAD

**Issue by balaji-dutt** [coreybutler/nvm-windows#652]
**NVM4W version:** 
``` sh
>nvm version
1.1.7
```

### My Environment

- Windows 10 Profession X64 (English)

-->

### Expected Behavior
* When I run the command `nvm use <nodejs-version>`,  the command should exit successfully. 

### Actual Behavior
* When I run the command `nvm use <nodejs-version>`,  I get an error message `exit status -1073741819:` which I believe is a Golang error code for Access Denied on Windows.

### Steps to reproduce the problem:
Steps to reproduce:
- Download NVM 1.1.7 `nvm-setup.zip`
- Extract & run the setup program with User that has Admin rights. Accept UAC prompt
- Accept default nvm install path
- Change nodejs install path to any other location: `C:\Users\<Username>\AppData\Roaming\nvm\nodejs` or even `C:\nodejs`
- Run `nvm install 12.16.2`
- Run `nvm use 12.16.2`

**Comment by SimonDever** [comment]
Are you running your nvm commands in a shell started with admin privileges as well?

**Comment by balaji-dutt** [comment]
> 
> 
> Are you running your nvm commands in a shell started with admin privileges as well?

Yes I have tried this with Admin privileges under `powershell` and `cmd` but I still get the same error message.

**Comment by coreybutler** [comment]
Did you uninstall prior versions of Node?

I cannot recreate this error on a clean Windows system following the same steps.

**Comment by balaji-dutt** [comment]
I'll admit to being baffled as well.

> Did you uninstall prior versions of Node?
> 
> I cannot recreate this error on a clean Windows system following the same steps.

I recently reformatted my PC so it is in effect a clean install. There is no installed Node version:

![ApplicationFrameHost_ivJlondNNJ](https://user-images.githubusercontent.com/3147070/127093272-f6d033ff-5b67-4334-a162-f171e45d8f1c.png)

There are some running Node processes, which are coming from Adobe Creative Cloud:

![node_G7bziU1sMC](https://user-images.githubusercontent.com/3147070/127093280-50ac2f92-5e26-4f2a-bbbb-56548c1e8102.png)

Is there some known conflict with these type of processes?

**Comment by coreybutler** [comment]
There is a possible conflict in the `PATH` environment variable. From a command prompt, run `echo %PATH%` and it should output a list of directories. If you see a path to a Node installation before the `NVM_SYMLINK`, then it will cause a conflict, but those usually occur when you try to execute node, not NVM4W. It shouldn't cause a conflict with with `nvm use`, but that doesn't mean another process isn't interfering with it.

If you find another installation of Node in your `PATH`, I'd suggest temporarily removing it, or moving the `NVM_SYMLINK` to the beginning of the `PATH`. 

Alternatively, you may want to move `NVM_HOME` to the front of the `PATH`. If you have another copy of NVM4W installed, it could also cause this behavior. I am unaware of anyone embedding NVM4W into their products, and I don't suspect Adobe is doing that.... but I also don't have any contrary evidence. 

The only other thing I noticed in your screenshot is an instance of nssm.exe running. That's the non-sucking-service-manager. It's a generic program that runs scripts as background services. I've seen folks use this with Node, unintentionally creating runtime conflicts. It's part of why I created [node-windows](https://github.com/coreybutler/node-windows), which uses an alternative.

Several of these ideas are outside the box, because this error just doesn't make sense in a clean install. Since I can't recreate it, these are "best guesses" that I hope lead you to a resolution.

**Comment by balaji-dutt** [comment]
> 
> 
> There is a possible conflict in the `PATH` environment variable. From a command prompt, run `echo %PATH%` and it should output a list of directories. If you see a path to a Node installation before the `NVM_SYMLINK`, then it will cause a conflict, but those usually occur when you try to execute node, not NVM4W. It shouldn't cause a conflict with with `nvm use`, but that doesn't mean another process isn't interfering with it.
> 
> If you find another installation of Node in your `PATH`, I'd suggest temporarily removing it, or moving the `NVM_SYMLINK` to the beginning of the `PATH`.
> 
> Alternatively, you may want to move `NVM_HOME` to the front of the `PATH`. If you have another copy of NVM4W installed, it could also cause this behavior. I am unaware of anyone embedding NVM4W into their products, and I don't suspect Adobe is doing that.... but I also don't have any contrary evidence.

Thanks for the suggestions. I did try making these changes but that did fix the error.

> The only other thing I noticed in your screenshot is an instance of nssm.exe running. That's the non-sucking-service-manager. It's a generic program that runs scripts as background services. I've seen folks use this with Node, unintentionally creating runtime conflicts. It's part of why I created [node-windows](https://github.com/coreybutler/node-windows), which uses an alternative.

To try and eliminate any possibility of AV scanners and other background services interfering, I rebooted Windows in Safe Mode. When I tried to run `nvm use` in Safe Mode under Admin mode, I still get the  `exit status -1073741819:` error.

> Several of these ideas are outside the box, because this error just doesn't make sense in a clean install. Since I can't recreate it, these are "best guesses" that I hope lead you to a resolution.

At this point, I'm pretty much ready to concede defeat as well. I had nvm working before on my PC. I would have thought a clean reinstall of Windows would make this easy but apparently it's the opposite. I don't have any urgent reason to require running multiple versions of node on my PC so I think I'll try switching to the regular Node installer and see if that works.

**Comment by balaji-dutt** [comment]
> 
> At this point, I'm pretty much ready to concede defeat as well. I had nvm working before on my PC. I would have thought a clean reinstall of Windows would make this easy but apparently it's the opposite. I don't have any urgent reason to require running multiple versions of node on my PC so I think I'll try switching to the regular Node installer and see if that works.

Switched to the regular Node installer which allowed me to get up and running. Going to chalk this one up as a heisen-bug on my PC and close it.
