### ISSUE TITLE
nvm Has been working fine and shows no errors, but windows will not let node run

### ISSUE THREAD

**Issue by DuckDuckDuckGoose** [coreybutler/nvm-windows#656]
![image](https://user-images.githubusercontent.com/71564682/131497180-bfcd8a60-f3c0-47eb-a1c8-1c7e4bb82613.png)
This is what happens when i try to run a js file that i KNOW is valid.
BTW, i downloaded the latest version (16.8.0 - atm) as x64 if that helps, sorry i cant be more specific i find all this very confusing...

**Comment by DuckDuckDuckGoose** [comment]
Oh and yeh i tried the common issues page, but could see anything that would help me
As i was using an admin terminal etc

**Comment by coreybutler** [comment]
Will it output just the version, i.e. `node -v`?

**Comment by DuckDuckDuckGoose** [comment]
Nope i get the same thing with -v, i managed to get 16.0.0 to work
but i did really want a newer version

**Comment by coreybutler** [comment]
If `node -v` doesn't work, then Node didn't install correctly.

I'm not clear about how you got Node 16.8.0, because you don't need to download anything (NVM4W does this for you). The normal process is to uninstall any prior versions of Node which were installed without NVM4W (because the official install conflicts with version managers). Next, install NVM4W with a user account that has administrative privileges. Then open a command prompt (powershell or terminal) and run `nvm install 16.8.0`, then `nvm use 16.8.0`. Finally, run `node -v` to confirm version 16.8.0 is available.

**Comment by DuckDuckDuckGoose** [comment]
Sorry for being confusing, when i said "downloaded" i mean that i ran `nvm install latest`. And then did exactly what you just described. Also yes i did uninstall all exisiting node stuff beforehand, unless im missing something i did follow the installation process correctly and as suggested

**Comment by antixrist** [comment]
Confirm this problem with 16.8.0, nvm 1.1.7, win7 x64

![image](https://user-images.githubusercontent.com/2387592/131746497-bdb69ec4-fdde-4d91-ac1f-1552d087e813.png)

**Comment by coreybutler** [comment]
Please try the new release: https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8

**Comment by coreybutler** [comment]
Closing due to age/activity.
