### ISSUE TITLE
NVM breaks on SPACES in a file path for Windows 10

### ISSUE THREAD

**Issue by wally96334** [coreybutler/nvm-windows#657]
After installation, I tried to run "nvm use" for the latest version of Node.

There is a SPACE in the path, and the app broke.
It does not take spaces into account for a file path.

------------------------------------------------------
C:\a01_temp>nvm install latest
Downloading node.js version 16.8.0 (64-bit)...
Complete
Creating C:\Users\Ron Anderson\AppData\Roaming\nvm\temp

Downloading npm version 7.21.0... Complete
Installing npm v7.21.0...

Installation complete. If you want to use this version, type

nvm use 16.8.0

C:\a01_temp>nvm use 16.8.0
exit status 1: 'C:\Users\Ron' is not recognized as an internal or external command,
operable program or batch file.

------------------------------------------------------

**Comment by IMTanuki** [comment]
And...if you grant nvm control of your current release, it moves the nodejs files to the nvm dir, at which point can't use either the new version or the original one, since it's been moved to the nvm dir. The only solution I found was to completely uninstall nvm, which also uninstalls both nodejs and all global packages - if it doesn't support path names with spaces, why does it let you migrate an existing nodej install to the new dir? Or why doesn't this get picked up in the nvm install process?

**Comment by inthmafr** [comment]
I've got the same issue too

**Comment by inthmafr** [comment]
Well... apparently this goes back a long time... I found this issue from 6 years ago: https://github.com/coreybutler/nvm-windows/issues/41
No idea why it's not fixed yet lol

**Comment by IMTanuki** [comment]
the only known fix is to completely uninstall nvm (and all versions of node that are controlled by nvm), then reinstall nvm under a dir with no spaces, which is an option during the install. But really, considering that at a minimum, the install could simply issue a warning about the dir name, this is a completely avoidable issue. Considering how long this has been out there, I have to conclude nvm is no longer maintained.

**Comment by calumcorrie** [comment]
Not sure how general [this answer](https://www.gitmemory.com/issue/coreybutler/nvm-windows/168/851013215) is but worked for me

**Comment by coreybutler** [comment]
Resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8
