### ISSUE TITLE
Can't use without admin account

### ISSUE THREAD

**Issue by AqlaSolutions** [coreybutler/nvm-windows#663]
When installing it I saw a UAC prompt to run as admin. So it installed into admin account. Afterwise I want to use it normally from my user account but neither "nvm" nor "bash" commands are not recognized there.

**Comment by AqlaSolutions** [comment]
Also I can't run uninstaller from my normal user account

**Comment by AqlaSolutions** [comment]
Manual installation didn't help:
```
C:\Users\Vlad>nvm
ERROR open C:\Users\Vlad\AppData\Local\nvm"\settings.txt: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by coreybutler** [comment]
Windows itself, not NVM4W, requires administrative privileges to perform many features, such as symlinking or accessing files in `C:\Program Files`. The next version, v1.1.8, adds support for some newer versions of Windows with less restrictive permissions. That will be released sometime this week.

I'm closing this because the permissions requirements come from Windows, not this app.
