### ISSUE TITLE
`nvm use` does not use version properly

### ISSUE THREAD

**Issue by AgainPsychoX** [coreybutler/nvm-windows#683]
**Issue:**

The `nvm use` subcommand seems to be not using version markers properly.

**How To Reproduce:**
```
C:\>nvm install ^14
Version 14.18.1 is already installed.

C:\>nvm use ^14
14.0.0
node v14.0.0 (64-bit) is not installed.
```

**Expected Behavior:**
Should `use` the 14.18.1.

**Desktop:**
 - OS: Windows

**Comment by kokiers** [comment]
```
D:\nvm> nvm use 13.2.0
Now using node v13.2.0 (64-bit)
D:\nvm> npx create-docusaurus@latest website classic
npx: installed 40 in 4.33s

Minimum Node.js version not met :)
You are using Node.js v10.24.0, Requirement: Node.js >=12.13.0.
D:\nvm> nvm ls

    13.8.0
    13.2.0
```
???  how to fix this error?

**Comment by coreybutler** [comment]
@AgainPsychoX - I forgot to mention, you can just run `nvm install 14` and it will install the latest version on the 14.x.x branch, or `nvm install 14.18` and you'll get the latest `14.18.x`.

@zlhartman - See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145

@kokiers - I suspect you did not uninstall a prior Node installation before installing NVM4W. The most common reason for this problem is the original Node installation precedes NVM4W in your `PATH`, meaning the OS never actually uses NVM4W... it uses the old Node installation. See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#uninstall-existing-node-installation-before-installing-nvm4w

**Comment by AgainPsychoX** [comment]
IMO it's inconsistency - I don't understand why it couldn't it be followed between 2 subcommands. For `install`, it should install newest version available (and it does so). For `use`, it should use newest version available (from installed ones), yet it fails.
