### ISSUE TITLE
In the non-administrator environment , command "nvm use lts" not work

### ISSUE THREAD

**Issue by DajianXu** [coreybutler/nvm-windows#704]
**Issue:**
nvm use lts not work in a non-administrator environment 

**How To Reproduce:**
1. in a non-administrator environment ,use "nvm install lts" install the latest long time server node  
2. use command "nvm use lts" . return exit status 1:{garbled code}
3. I debug it and change the "%s" cmd /C mklink /D "%s" "%s" to "%s" cmd /C mklink /J "%s" "%s" and It works.

**Desktop:**
 - OS: Windows 10 17763.1879

**Comment by coreybutler** [comment]
Microsoft Windows requires administrative privileges to modify symlinks.

The change you're making specifies a junction instead of a directory symlink. This does not work across different disks, i.e. it will not work on `D:\` (as opposed to `C:\`), which is particularly problematic in enterprise environments with shared disks and NAS/SAN drives. It is a sweeping change that would impact hundreds of thousands of users if I were to release it.

I do recognize this would help many users. I am hoping to give users a choice whether they want to use symlinks or junctions in [rt](https://github.com/coreybutler/nvm-windows/discussions/565#discussioncomment-58112) (the successor project).

**Comment by ldwqh0** [comment]
you can build nvm your self to change the "mklink /D" to "mklink /J"
step 1:
  install nvm normal, set the node.js symblink path to your owner path, e.g "driver/users/username/appdata/local/nodejs"
  * it is very important ,because "mklink /d" require admin privileges , the "mklink /j" not require  admin privileges but it can not create link in a system director.
step 2:
  install go enviroment
step 3:
  clone the code
step 4: 
  edit the file src/nvm.go ,find and replace the "mklink /D" to "mklink /J"
step 5:
  build nvm.go
```bash
cd src
go build nvm.go
```
step 5:
  move your nvm.exe to your install direcort

now you can use nvm without admin privileges .
