### ISSUE TITLE
[1/2/2022]: Installing Windows Build Tools with NVM-Windows.

### ISSUE THREAD

**Issue by Lermatroid** [coreybutler/nvm-windows#718]
Now that windows build tools is supposed to be installed via the Node JS installer, is there/could there be a way for us to do this via nvm-windows?

The installer on NPM has some issues, such as the latest version freezing powershell when installing and older versions having security vulnerabilities.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
The MSI installer is responsible for any additional build tool installation, but the MSI installer does not allow multiple versions to be installed simultaneously. This is why version managers use the zip archives instead.

In order to do what's requested, NVM4W would have to recreate the build tools installation process. That's not a trivial effort, and it's not something I have time to do in this project. However; it is something I'll look into for [rt](https://github.com/coreybutler/nvm-windows/discussions/565#discussioncomment-58112).
