### ISSUE TITLE
NPM is installed every time

### ISSUE THREAD

**Issue by deekeh** [coreybutler/nvm-windows#737]
Whenever I try to install a new version of Node using `nvm install <version-number>`, it also installs the same version of NPM again. The application should have a check to see if:
1. NPM is already installed
1. the installed NPM version matches the one it is trying to install

It should proceed to install a fresh copy of NPM only after any of the cases fail.

**Comment by coreybutler** [comment]
Are you reinstalling an existing version of Node?

There is no version of Node that ships with the same version of npm, so the only way a conflict would arise is if you're installing a version _again_.

**Comment by deekeh** [comment]
Currently, I have installed 3 Node versions on the system:
```
* 14.18.3 (Currently using 64-bit executable)
    12.22.6
    10.21.0
```

I think it installed the same NPMs every time when I installed these. As you are implying that all Node versions have a different version of NPM for them, it seems fine. I'll just confirm that this is really the case.

**Comment by coreybutler** [comment]
I was mistaken, it looks like the 12.x and 14.x branches both use npm 6.14.15. However; Node 10.21.0 uses npm 6.14.4. The full list can be found at https://nodejs.org/download/release/index.json

That said, _most_ versions of Node have a different version of npm shipped with them.

Keep in mind, this still isn't a bug. NVM4W intentionally installs an isolated copy of npm for each version of Node. This allows developers to add global modules to each instance of Node without interfering with each other.

There is one possible improvement. NVM4W _could_ store the installation source files for each version of npm. When a new version of Node is installed, it could search for any pre-existing downloads before downloading a new copy of npm. 

I don't think the work-to-reward tradeoff is worth it. The file system will become bloated if NVM4W stores/archives each version of npm it downloads, especially when it won't really be used very often. It cannot use an "existing" installation from a previously installed version of Node because the previous version may include globally installed modules or native add-ons that do not work in the new version (i.e. not a clean install of npm).

If people are concerned about bandwidth consumption, please make a note in the [discussions](https://github.com/coreybutler/nvm-windows/discussions). I'd like to know how big of a concern this is for people/organizations. So far, most concerns I've been made aware of have to do with how much diskspace Node/npm takes up.
