### ISSUE TITLE
Garbled error message when `nvm use` fails in Japanese environment.

### ISSUE THREAD

**Issue by ironsand** [coreybutler/nvm-windows#740]
When I run `nvm use 17.4.0` without an admin privilege, the command fails with garbled error messages.

### powershell
```
> nvm use 17.4.0
exit status 1: ���̑��������s���邽�߂̏\���ȓ����������܂����B
```

With admin privilege, the command runs successfully.

```
$ nvm use 17.4.0
Now using node v17.4.0 (64-bit)
```

I'm using in Japanese environments.
What should I do to show readable error message?

**Comment by coreybutler** [comment]
`exit status 1` uses the error message from the operating system, so I'm not sure why it's garbled.

However; the [common issues (exit 1, exit 5, access denied)](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145) should provide an answer. The bottom line is you need admin privileges to run `nvm use`.

I'll leave this open since the garbled message may be a bug... I'm just not sure how to fix this and I do not have a Japanese version of Windows to test on.

**Comment by gadfly3173** [comment]
> I'll leave this open since the garbled message may be a bug... I'm just not sure how to fix this and I do not have a Japanese version of Windows to test on.

![image](https://user-images.githubusercontent.com/28685179/155479319-bd9f6c5b-c349-4abc-83c2-b079bca92115.png)
Chinese version of Windows has the same problem. This kind of garbled message is often been known as read GBK-encoded Chinese in UTF-8
