### ISSUE TITLE
nvm use  exit status 1: Access is denied. after nvm install

### ISSUE THREAD

**Issue by squidjam** [coreybutler/nvm-windows#755]
**Issue:**
After a clean install of NVM due to the mismanagement of the previous version, now I have an issue where calling for nvm use on a fresh nvm install gives me the following error message.

exit status 1: Access is denied.

**How To Reproduce:**
Under windows 10.

- Uninstall completely the previous version of NVM
- Install the newest version double clicking on the icon.
- Answer yes to the prompt to allow nvm-setup to continue 
- The installation continues correctly (Next, next...)
- Open a PowerShell and issue nvm install 16
- nvm installs the latest (16.14.0 at the moment)
- after it's finished, issue nvm use 16.14.0

**Expected Behavior:**
nvm should make node version 16.14.0 available as the node installation.

**Observed Behavior:**
An error message is shown saying that:
exit status 1: Access is denied.

**Desktop:**
 - OS: Windows 10 latest

**Additional context:**
This is a blocking issue.
One should not need to use elevated administration rights to set the version.

**Comment by coreybutler** [comment]
Have you gone through the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145) guide?

_Windows_ requires elevated privileges to change the install (i.e. change a symlink)... just like any installation. Enable developer mode if you need less restrictive permissions.

**Comment by squidjam** [comment]
What if someone don't have this kind of control over their equipment due to company policies... :(
I mean, I didn't use to need to run PowerShell as an Administrator to get to change the version of node before.
Is this something new?

**Comment by Clonkex** [comment]
@coreybutler On the previous version of nvm I was using (I think 1.1.7?) it would bring up two separate UAC dialogues when I ran the commands in a non-elevated cmd. Today I updated to 1.1.9 and now I have to manually run cmd as admin beforehand, otherwise I just get the same access is denied errors of the OP. This is somewhat inconvenient, though luckily I don't use nvm that often.

**Comment by coreybutler** [comment]
@squidjam - admin privileges aren't required to execute node, but they've always been required to switch the active version if you use a Windows protected directory (like `C:\Program Files\Nodejs`). Windows requires admin or developer privileges to create symlinks, which is how NVM4W implements version changes.

To @Clonkex's point, what's "new" since 1.1.7 is that the UAC prompt is no longer triggered. This behavior was changed due to a high volume of user requests to use developer mode instead of UAC prompts. At the time, nobody expressed opposition to this change. However; many users are requesting the old functionality. I don't have time to implement both approaches, so I am going to leave it as is for now and focus on a better approach for the future. In [rt](https://github.com/coreybutler/nvm-windows/discussions/565#discussioncomment-58112), I am planning to either give users the choice or (if possible) auto-detect the environment to accommodate both UAC and developer mode options.

**Comment by Clonkex** [comment]
> developer mode instead of UAC prompts

Developer mode of what? Windows? Do you mean we're expected to enable developer mode to use nvm-w? That would be strange.

> At the time, nobody expressed opposition to this change.

This is a common flaw with requests for change. Only the people that actually want the change to occur will seek out communication channels (negative bias). It may only be a minority that want the change, but since everyone else is already happy with the current state and don't regularly review communication channels, it _appears_ as though the majority want the change. Only after the change is made does the real majority speak up.

I don't think there's a good solution unless your software has a notification system to request comments, but it's worth keeping in mind at least.

**Comment by coreybutler** [comment]
Yes, developer mode of Windows. It's the only non-admin way to be granted permissions to create symlinks without UAC prompts.

The support was based on a survey where people could but didn't oppose. Still, your point stands. This project gets many contradictory requests, so it's a bit of balancing act. This particular split of preferences is something I think can be handled though, in the successor project.
