### ISSUE TITLE
Enter the absolute path where the nvm-windows zip file is extracted/copied to:

### ISSUE THREAD

**Issue by olemarius** [coreybutler/nvm-windows#775]
**Issue:**

I keep getting this error on nvm 1.1.9 installed with all defaults when running pnpm install
Nvm root is `Current Root: C:\Users\olema\AppData\Roaming\nvm`
I've tried reinstalling as well, same issue. Also tried different node versions. 

**How To Reproduce:**
- Windows 11
- Install nvm 1.1.9
- nvm install 16.14.2
- nvm use 16.14.2
- npm install -g pnpm 
- pnpm install --shamefully-hoist

Then I get prompted with `Enter the absolute path where the nvm-windows zip file is extracted/copied to:`

so I enter `C:\Users\olema\AppData\Roaming\nvm

which prints
```
SUCCESS: Specified value was saved.

SUCCESS: Specified value was saved.
\Common was unexpected at this time.
```

then next time I run pnpm install --shamefully-hoist I'm not asked to enter path, just met with the same:
```
SUCCESS: Specified value was saved.

SUCCESS: Specified value was saved.
\Common was unexpected at this time.
```

**Expected Behavior:**
Not getting prompted by "Enter the absolute path where the nvm-windows zip file is extracted/copied to:"

**Comment by coreybutler** [comment]
I'm not sure why this is happening, but it's clear the install.cmd file is running.  I'm not sure when I'll get a chance to look into this.

**Comment by dibalavs** [comment]
Hi, I have the same issue.
Is there any fix for this bug?

my script output was:

`\Common was unexpected at this time.
C:\Work\nvm-noinstall>(echo PATH=C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\Program Files (x86)\Kaspersky Lab\Endpoint Agent\;C:\Work\bin;C:\Program Files\Pandoc\;C:\Users\locadm\AppData\Local\Microsoft\WindowsApps) > c:\Work\nvm-noinstall\PATH.txt`

Looks like script does not like "Common Files"

**Comment by dtechfish** [comment]
I'm having the same issue, was anyone able to fix?

**Comment by schnippe** [comment]
Please change install.cmd to quote the PATH Variable like that: 

(echo PATH=%PATH%) > %NVM_HOME%\PATH.txt
--->
(echo PATH="%PATH%") > %NVM_HOME%\PATH.txt

**Comment by cesarAlvaradoDiaz** [comment]
Delete/remove/uninstall the version of node in your "C:\Program Files\nodejs" directory. To the point where there is no more "nodejs" directory at all.
Delete the existence of nvm (C:\Users\xxx\AppData\Roaming\nvm), basically, manually delete the nvm dir.
Download your desired version of nvm (https://github.com/coreybutler/nvm-windows/releases)

**Comment by Andrewiski** [comment]
Maybe the install.cmd should be renamed to installnvm.cmd its getting put on the path so any install call on windows is executing nvm's install and giving this prompt.  ie user type "install express"  instead of "npm install express"

**Comment by duzenko** [comment]
This happened to me when installing Claude Code in git-bash instead of windows-cmd
https://code.claude.com/docs/en/setup

**Comment by b-c-lucas** [comment]
In case anyone runs into this in 2026 and beyond:
- I had nvm-windows installed and running well for almost 2 years, with the latest version running for over a year.
- I recently installed Claude Code according to [the instructions](https://code.claude.com/docs/en/setup), as @duzenko mentioned, though I did so via PowerShell.
- I went back to run a project that had been working, only to encounter the error at the root of this issue.

What I didn't realize is that somehow, behind the scenes, the locations of my nvm setup somehow got moved: I finally deduced that I had installs for nvm within each of the Roaming and Local folders of my AppData:
- I removed the nvm folder within Roaming (as suggested by @cesarAlvaradoDiaz), since the Local install was newer.

Now everything is back to working. I hope this refresh helps others remedy their problems!
