### ISSUE TITLE
Node installed with the wrong NPM version

### ISSUE THREAD

**Issue by thany** [coreybutler/nvm-windows#789]
**Issue:**

**How To Reproduce:**
1. `nvm install 12.6.0`
2. `nvm use 12.6.0`
3. `npm i -g yarn`
4. See error:

```
npm does not support Node.js v12.6.0
You should probably upgrade to a newer version of node as we
can't make any promises that npm will work with this version.
You can find the latest version at https://nodejs.org/

added 1 package, and audited 2 packages in 2s

found 0 vulnerabilities
```

5. Run `npm -v` to discover it's using NPM 8.6.0.

**Expected Behavior:**
I don't know which version of NPM is right for Node.js 12.6.0, but 8.6.0 is not the correct one.

**Desktop:**
 - OS: Windows 10

**Comment by coreybutler** [comment]
The version of npm that ships with Node 12.6.0 is `6.9.0` (see https://nodejs.org/dist/index.json)

I cannot recreate this error:

<img width="539" alt="image" src="https://user-images.githubusercontent.com/770982/163435398-db3a80fa-aaca-46d6-9369-f2a70d14c84a.png">

**Comment by thany** [comment]
Good for you. It works on your machine.

Just stating this, essentially is counter-productive and only adds work. As you stated so rudely in my other issues.

**Comment by coreybutler** [comment]
Instead of being condescending in every post, perhaps you could consider the help being offered. 

The point of sharing what I did was to show that the steps you provided do not produce the stated error in a clean environment. I cannot troubleshoot something I cannot recreate. Furthermore, I'm providing context in an effort to help you troubleshoot/compare your environment.

The details you've provided suggest something else is going on in your environment. The primary clue is step #5, which states npm version 8.6.0 is installed with Node 12.6.0. If you look at the link I provided in my prior post, you'll see that Node 12.6.0 ships with npm 6.9.0, not 8.6.0 as described. NVM4W uses that URL to determine which version of npm to install. As the screenshot I provided indicates, NVM4W installs npm v6.9.0. 

The primary issue I see is an assumption that NVM4W is responsible for installing npm 8.6.0. NVM4W only downloads the npm version assigned by Node. The far more likely cause of this is running `npm install -g npm`. Sometimes this is just done by mistake, and sometimes it is done by scripts (such as pre/post-installers, cli tools, environment setup scripts, etc).

If you want to troubleshoot this, uninstall/reinstall Node v12.6.0. Removing it should remove the npm installation as well. Reinstalling it should provide the default version of npm (6.9.0).

**Comment by coreybutler** [comment]
Each version of Node is isolated in its own directory, with its own installation of npm. When you switch to a new version, npm changes too. If you update/upgrade npm (`npm install -g npm`), it will only update npm for the current version of Node... but it permanently updates it (same behavior as if no version manager exists).

In order for your system to show npm v8.6.0 instead of 6.9.0, it had to be updated somehow. If you don't remember doing this, then it's likely something else did it for you silently. This is most commonly done with npm's [preinstall](https://docs.npmjs.com/cli/v6/using-npm/scripts#npm-install) script. Some package maintainers include a preinstall scripts to automatically run `npm install -g npm` to assure you have the latest version of npm (since npm has had many issues/breaking changes over the years). This is also commonly done with npx scripts (though npx only affects newer versions of npm), or with CLI tools.. especially other tools that try to help update your dev environment for you. It's not a good practice to update the environment without the end user knowing, but it's relatively common.

The bottom line is I don't know how npm 8.6.0 was installed or if any of the aforementioned circumstances apply. Those are the circumstances that a) make an environment "not clean" and b) NVM4W cannot account for.

**Comment by VividWombat** [comment]
a tip for those who get this problem. if you installed NPM previously, or outside of NVM, then check your PATH settings. if NPM is in your path, then NVM cant manage the version in use. I had this problem, and deleting path to NPM solved this

**Comment by lutzklai** [comment]
Ran into a similar issue with node `14.15.4`. npm `7.24.2` was installed for some reason instead of npm `6.14.10`. I tried @VividWombat 's suggestion. Running `which npm` did bring up the proper nvm path.

We ended up uninstalling and reinstalling the node version. The correct npm version was installed.

```
nvm uninstall 14.15.4
nvm install 14.15.4
```
