### ISSUE TITLE
cant set npm  config 

### ISSUE THREAD

**Issue by MadShura** [coreybutler/nvm-windows#795]
**Is your feature request related to a problem? Please describe.**
cant set npm  config 

**Describe the solution you'd like**
i use nvm （v:1.1.9） and install node lts 
after that , i try to run `npm config set prefix "E:/NPMdownload"` 
and ` npm i XXXpackage` ,its still downloaded in my personal user folder .
 Ability to correctly modify the npm download directory

thanks

**Comment by coreybutler** [comment]
NVM for Windows has nothing to do with npm (other than installing it). In other words, this is an issue with npm.

In an effort to try to be helpful, the only issue I see with the command is that it uses forward slashes (commonly used in Linux/macOS) instead of backslashes (used in Windows). In other words, try `npm config set prefix "E:\NPMdownload"`.
