### ISSUE TITLE
npm use vs install consistency

### ISSUE THREAD

**Issue by coldsc** [coreybutler/nvm-windows#797]
```nvm install 14``` assumes you want to install the latest version of node 14.
```nvm use 14``` does not assume you want to use the latest version of node 14.

![image](https://user-images.githubusercontent.com/30379671/167046185-fb029ccd-3ce0-4a13-aa20-24fd98621db2.png)

**Solution**
Have ```nvm use X``` use the latest version of X available.

**Alternatives**
Have ```nvm use``` show installed alternatives of the same major version if the exact version (e.g 14.0.0) is not installed.

Apologies if this has already been brought up.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by xavierfoucrier** [comment]
@coldsc, good point.

`nvm use 14` should switch to the latest `nodejs` version `14` currently installed.

Because, most time you need to `nvm list`, then read the version number you want to use, then type `nvm use **.**.**`.
Would be good to have this feature integrated inside the CLI.

cc @coreybutler :v:

**Comment by coldsc** [comment]
Closed as it is addressed in multiple other posts.
