### ISSUE TITLE
inconsistent npm version in "npm run"

### ISSUE THREAD

**Issue by FanghanHu** [coreybutler/nvm-windows#817]
**Issue:**

The npm command in a package.json script does not use the npm version selected by nvm.

**How To Reproduce:**

1. create a new script in package.json 
```
"scripts": {
     "show-version": "npm -v"
}
```
2. run the script

**Expected Behavior:**

get the same version of npm in npm run script and outside it.

<img width="602" alt="image" src="https://user-images.githubusercontent.com/3207447/172445248-4a9eb0c0-8478-4e9a-84ef-536f8352f98e.png">

**Comment by coreybutler** [comment]
NVM4W isn't a part of this at all. NVM4W merely sets a symlink to the Node.js installation, it does not interfere with npm.

While I can't say with certainty, the issue could be the mingw64 shell. npm may not be picking up the right filepath since the shell is using unix paths like `/d/workspace/lenwell-pos` instead of Windows paths like `D:\workspace\lenwell-pos`.
