### ISSUE TITLE
:disappointed:I understand it's not NVM, but I feel it's too far away from NVM. 

### ISSUE THREAD

**Issue by natebowang** [coreybutler/nvm-windows#831]
Here is my experience using nvm-windows: 
- I downloaded and installed v1.1.9;
- Try to use _.nvmrc_ and find nvm-windows hasn't supported it yet. What is the reason to use nvm without .nvmrc? Randomly input some version after switching to another project? 
- Then I assume randomly inputting some number is acceptable and got Access is denied error. 
- Then, I searched for the issue and found two open issues related to the same error and many diverged solutions in them. 
- The downgrade solution seems promising and simple, so I go to the release page. 
- I can't find the download URL for 1.1.8 on the release page after a while. 
- The only thing helpful is there is an uninstaller in v1.1.9.  

I complained because there is NVM in the name. And I came here with expectations. I never had this pain when I used NVM. 
I guess many others too.

**Comment by lucasalmeida92** [comment]
Having similar experience haha! ;'/
Did you manage to install 1.1.8 version?

**Comment by coreybutler** [comment]
All downloads are on the release page. Standard Github releases.

Review the README, discussions ([Welcome thread](https://github.com/coreybutler/nvm-windows/discussions/565#discussioncomment-58112)) and the [wiki](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported). There's a lot of information about the project and its differences from other version managers.

I'm closing this, because there isn't a technical issue here.
