### ISSUE TITLE
Install npm 8.13 with node 16.16

### ISSUE THREAD

**Issue by hyvyys** [coreybutler/nvm-windows#832]
**Issue:**

Installing node 16.16 installs npm 8.11 which is broken and cannot update itself. Running `npm i -g npm@latest` returns error:

```
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Unexpected token '.'
```

Fixing up the 4 npm files by replacing `-g` with `--location=global` as advised on [StackOverflow](https://stackoverflow.com/questions/72401421/message-npm-warn-config-global-global-local-are-deprecated-use-loc/72947173?noredirect=1#comment128861776_72947173) doesn't help either:

```
npm i --location=global npm@8.13
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Unexpected token '.'
```

**How To Reproduce:**
1. Install node 16.16 on Windows
2. Try using npm

**Expected Behavior:**
npm working correctly.

**Comment by coreybutler** [comment]
Thank you for reporting.

As a general policy, this project does not attempt to resolve specific upstream problems with npm unless Node itself does something unique. Otherwise I'd end up supporting something npm should be supporting. These types of issues will be supported in the upcoming commercial edition of NVM4W's successor (Runtime/rt).

The workaround for this is to manually install an updated version of npm from the [npm releases](https://github.com/npm/cli/releases). The old npm directory in `node_nmodules` can be replaced with the new one.
