### ISSUE TITLE
nvm 切换node版本后 npm无法升级

### ISSUE THREAD

**Issue by A2Data** [coreybutler/nvm-windows#841]
C:\Users\Jack>npm -v
6.14.16

C:\Users\Jack>npm install -g npm
npm ERR! code EEXIST
npm ERR! path C:\Program Files\nodejs\npm.cmd
npm ERR! Refusing to delete C:\Program Files\nodejs\npm.cmd: is outside C:\Program Files\nodejs\node_modules\npm and not a link
npm ERR! File exists: C:\Program Files\nodejs\npm.cmd
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jack\AppData\Roaming\npm-cache\_logs\2022-07-29T13_08_57_093Z-debug.log

**Comment by coreybutler** [comment]
This is an npm issue, not an NVM4W issue. NVM4W doesn't touch npm once it is installed (remember, this is _**npm** install_, not _nvm install_).

If my memory serves correctly, this particular issue is caused by a hard-coded value in the npm source code in this particular version. It will not allow itself to be removed from a symlinked directory. The issue is ignored by npm because v6.14.16 is no longer actively developed.
