### ISSUE TITLE
Installer: making any per-user area changes in an admin install

### ISSUE THREAD

**Issue by BurtHarris** [coreybutler/nvm-windows#864]
**Issue:**  The build script issues a warning from innosetup, saying:

> Warning: The [Setup] section directive "PrivilegesRequired" is set to "admin" but per-user areas (userappdata) are used by the script. Regardless of the version of Windows, if the installation is running in administrative install mode then you should be careful about making any per-user area changes: such changes may not achieve what you are intending. See the "UsedUserAreasWarning" topic in help file for more information.

The message is right, it can cause problems to mix per-user settings into an admin install.   I will submit a PR that addresses the problem.

**How To Reproduce:**
1. Open CMD prompt in project directory 
2. BUILD

**Expected Behavior:**
Clean build

**Desktop:**
 - OS: Windows 11

**Comment by ViliusS** [comment]
I like this idea of having ability to install NVM having only user permissions, but it's probably a general question if that's currently supported? Since NVM relies on creating a symlink when running `nvm use X.Y` it would still mean that app is unusable without having admin permissions. Symlink creation and modification requires admin.

**Comment by BurtHarris** [comment]
@ViliusS, that is an oversimplification.  There is an alternative to symlink that can work without elevated permissions.  These are called an NTFS junction points, but they do require enabling Windows developer mode.   Corey understands this, and we have discussed it.  For reasons of his own, he's not interested in making the change at this point but is keeping these issues open for later consideration..    

I considered a fork, I found another github tool called [Volta](https://github.com/volta-cli/volta) that already uses junction points for the same sort of functionality as NVM for windows.     Volta fits my needs quite well.

**Comment by ViliusS** [comment]
Maybe, like you say, it's oversimplification, but it doesn't change the fact that currently NVM requires administrator privileges to be used. Even if you consider Developer mode, it can only be enabled having administrator permissions.

**Comment by coreybutler** [comment]
One reason for not moving to junctions is the fact they do not work across mapped directories. There are many organizations using mapped drives/directories, so shifting NVM4W to junctions would immediately render the tool useless for developers in these environments. Junctions work around a safeguard explicitly defined in Windows (i.e. symlinks), which is a problem in many company environments. That makes this a major breaking change.

I'm not prepared to make breaking changes at this time. As explained in the wiki, I'm [feature-freezing NVM4W in order to work on Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).

I'm closing this issue, but will leave the PR open so the concepts surface during the Runtime development effort.
