### ISSUE TITLE
Download fails with "file being used by another process"

### ISSUE THREAD

**Issue by ajmeese7** [coreybutler/nvm-windows#877]
**Issue:**

Download fails for unknown reason.

**How To Reproduce:**

```
PS C:\Users\ajmeese7\Documents\app-nodejs> nvm install 16.15.1
Downloading node.js version 16.15.1 (64-bit)... 
Download failed. Rolling Back.
C:\Users\ajmeese7\AppData\Roaming\nvm\v16.15.1\node.zip
Rollback failed. remove C:\Users\ajmeese7\AppData\Roaming\nvm\v16.15.1\node.zip: The process cannot access the file because it is being used by another process.
Could not download node.js v16.15.1 64-bit executable.
```

**Expected Behavior:**

I expect the ZIP file to be accessible to the process, there is nothing preventing it from doing so. And I expect the download to work, it downloads an empty ZIP file because the download fails with no information as to why.

- OS: Windows 10 19045.2130

**Comment by coreybutler** [comment]
This could be a problem with the remote server, or there could have been a network glitch. In the past, there have been reports of this caused by:

- Remote server TLS/SSL certificate updates
- Remote server downtime/maintenance
- Add/removal of a mirror server
- Local proxy interrupted
- Local network temporarily interrupted (has happened w/ satellite connections)
- Lack of permissions to write to the temp directory

I'm not sure if any of these fit your situation, but the remote servers seem to be working now.

<img width="399" alt="image" src="https://user-images.githubusercontent.com/770982/200088035-38d4cab5-6022-4751-85e5-8040e8157391.png">

My advice is to wait a little bit, then try again.

**Comment by ajmeese7** [comment]
Looks like the server may have been having issues, it works fine now as you predicted. Thanks!
