### ISSUE TITLE
2022-11-25: Allow non-admin users to use User env variables

### ISSUE THREAD

**Issue by jakubgosk** [coreybutler/nvm-windows#889]
Hi, 
I got myself a non-install version of nvm-windows since I don't have admin access. Unpacked, configured NVM_HOME and NVM_SYMLINK in User Env Variables 'cause I can modify those, added some things to Path. 
Nvm installes versions properly but `nvm use` command requires login with admin account. I guess that's to alter NVM_SYMLINK in System Env Variables. Could you add a way to tell the software which env variables can it use? With that change nvm-windows would work perfectly not only for me.

By the way, after using `nvm use x.x.x` and then cloising pop-up to login with admin account, terminal still ends with "Now using vx.x.x" which is not true.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr> 
</table>

**Comment by coreybutler** [comment]
Windows requires administrative privileges to create any type of symlink. It's not about the env variables, it's about the underlying mklink function.

**Comment by jakubgosk** [comment]
Thanks for answering. 
So would it be possible to add some kind of flag in settings.txt for non-admin users, that would limit nvm-windows just to changing value of %NVM_SYMLINK% in User Env after command `nvm use`.
That would make this already cool software useful to download specific versions and quite effortlesly change version. After adding %NVM_SYMLINK% to Path that would work, of course terminal restart still 'd be needed. However better than nothing for non-admin users I thing.

By the way, Readme could mention something about non-install version, f.e. that file settings.txt is required or env variables like NVM_HOME and NVM_SYMLINK need to be created.

**Comment by coreybutler** [comment]
@jakubgosk NVM4W could set user env vars, but this goes down a rabbit hole I'm not prepared to go down with NVM4W. To be clear, there is work happening in this space, but it's in [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime). Bottom line, there is a better approach than relying on the settings file, but the return on effort is better with Runtime than NVM4W.

In the meantime, and I may be off base with the intent of your question, but you may find [this approach](https://github.com/coreybutler/nvm-windows/issues/671#issuecomment-1248511761) helpful as a workaround.

**Comment by minijus** [comment]
Would using junction `/J` instead of link `/D` in `mklink` be an option? Maybe the flag could be configurable via `settings.txt`?

**Comment by coreybutler** [comment]
@minijus - that's a different issue that has been brought up many times in the past. Junctions will not be used in NVM4W because they do not work across shared disks (which would break for hundreds of thousands/millions of users). 

Making it user-configurable is something planned for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime)... but I'm not going to make major breaking changes to NVM4W when Runtime can resolve them in a more effective/safer way.

**Comment by minijus** [comment]
Allowing it to configure for user while keeping `/D` as default wouldn't be a breaking change. Users that do not use shared disks could solve issues with requirement for elevated privileges by having this options.

**Comment by coreybutler** [comment]
@minijus - _again_, this is a different issue. Please read the [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) page, specifically [this bit](https://github.com/coreybutler/nvm-windows/wiki/Runtime#:~:text=The%20other%20thing%20slowing%20down%20Runtime%20development%20is%20this%20project.%20So%2C%20I%27m%20freezing%20feature%20development%20on%20NVM%20for%20Windows.). A change like that still requires time and testing... it's not just about the code. There is already a workaround (as mentioned earlier) and a plan for resolution (via Runtime).

I'm not going to speak about this more in this thread because it's off topic from the original post. Further conversation can continue in the discussions if desired, but I hope these points are clear.
