### ISSUE TITLE
nvm trying to retrieve the wrong SHASUMS256.txt file

### ISSUE THREAD

**Issue by terrycoughlan** [coreybutler/nvm-windows#900]
I have had to uninstall nvm and reinstall it, when I try to install one of the older node versions i.e. 14.20.1 I get the following:

Could not retrieve https://nodejs.org/dist/latest/SHASUMS256.txt 
**BUT** 
the **url** should show the version of node i'm trying to install and not **latest** - **it should** be trying to download this text file with correct version in the url: 
https://nodejs.org/download/release/v14.20.1/SHASUMS256.txt

Any idea on how to fix this, so that it will try to download the correct SHASUMS256.txt file?

![image](https://user-images.githubusercontent.com/2589463/206686688-ff872085-9c20-4366-a6f8-99f9348d4188.png)

FYI - @coreybutler

**Comment by coreybutler** [comment]
@terrycoughlan The last line of the output identifies your specific problem. There is no internet connection. 

By default, the latest SHASUM is retrieved when NVM4W thinks it needs to retrieve the latest version (https://github.com/coreybutler/nvm-windows/blob/53bc08dfed5a1ec99a6d6fb8f4771f9de993b3de/src/nvm.go#L866). In your case, it does not recognized v14.20.1 as a version because you have no internet connection. It cannot retrieve the list of Node versions.
