### ISSUE TITLE
NVM doesn't work. No NodeJS in use after: nvm use x.x.x

### ISSUE THREAD

**Issue by b0** [coreybutler/nvm-windows#901]
**Issue:**
Before installing nvm, I removed my previous nodejs version and followed the instructions in the readme how to remove the remaining files here: https://github.com/coreybutler/nvm-windows#star-star-uninstall-any-pre-existing-node-installations-star-star

After installing nvm as administrator I proceed and installed 3 different nodejs versions using nvm . 

After that, in new powershell and new cmd(both as admin) I tried using nvm. 
nvm appears to be working but it is not. 

I am suspicious of sym link because **there is no**  C:\Program Files\nodejs folder. 
I can see it specified in the environment variable NMV_SYMLINK. NVM_HOME  is also specified.

**Expected Behavior:**
I expect to be using node.

**Screenshots:**
![nvm_issue](https://user-images.githubusercontent.com/1926879/207403210-25ed2ede-836a-4549-945d-beb38b5395e1.png)

**Desktop:**
 - OS: Windows 10

Is there a verbose option to using nvm or any logs?

BR

**Comment by coreybutler** [comment]
It sounds like something went awry in the installation, but I'm not sure why.

Do you have a `path` in your settings.txt file?

**Comment by Hicks-Josh** [comment]
I'm having the same issue here's my settings files:
```
root: C:\Users\me\AppData\Roaming\nvm
path: C:\Program Files\nodejs
```

**Comment by b0** [comment]
Yes, root and path are correctly set.

> root: C:\Users\XXX\AppData\Roaming\nvm
> path: C:\Program Files\nodejs

**Comment by coreybutler** [comment]
These settings files look correct, so you should be able to manually make the symlink to an installed version, i.e. 

```sh
mklink /D "C:\Program Files\nodejs" "C:\Users\XXX\AppData\Roaming\nvm\vX.X.X"
```

This is what `nvm use x.x.x` is supposed to do for you. If this works, you should be able to `nvm use ...` for anything else. If it fails, post the error message here.

Bottom line is the installer should have done this for you, but for some reason it apparently did not. Doing it by hand will either correct the glitch or (hopefully) provide info to troubleshoot with.

**Comment by b0** [comment]
After trying that in cmd I get this:

> You so not have sufficient privilege to perform this operation.

Currently I am reading this on SE [Got not sufficient privileges message in CMD when logged on as administrator](https://superuser.com/questions/129299/got-not-sufficient-privileges-message-in-cmd-when-logged-on-as-administrator)

It seems this is repeated issue.

**Comment by coreybutler** [comment]
You need to execute the commands as an admin, or you must have permissions to create symlinks. See the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145).

For users running in developer mode who can create symlinks but can't write to protected directories (like `C:\Program Files`), I recommend changing the path in your `settings.txt` to `C:\nvm`, then running `nvm use`. 

This project will not be using junctions because they do not work across mapped directories (therefore breaking everything for companies using NAS/SAN for their code bases). There are several closed issues where these ramifications have been discussed at length, but the main one is it would break installations for many people using NVM4W in their company. Since junctions would be a major breaking change, I've been toying with the idea of giving users a choice between symlinks and junctions in [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) instead.
