### ISSUE TITLE
Nvm list not recognizing installed Node.js versions

### ISSUE THREAD

**Issue by jjlin526** [coreybutler/nvm-windows#912]
**Issue:**
- No Node.js versions recognized by NVM using `nvm list` or `nvm list available`. Output is "No installations recognized" and an empty table, respectively.
- `nvm install 16.17.1` fails even though `node -v` outputs a valid Node version: v16.17.1
- `nvm install latest` causing runtime error

**How To Reproduce:**
1. Delete existing nodejs folder in C:\program files\ and uninstall Node.js 
2. Install and run nvm-setup.exe
3. Install Node.js v16.17.1 (64 bit)
4. Run `nvm list` or `nvm list available`
5. Check Node installation using `node -v`
6. Run `nvm install 16.17.1`
7. Run `nvm install latest`

**Expected Behavior:**
- `nvm list` should list Node.js versions
- `nvm install 16.17.1` should install the Node.js version so that it can be used by `nvm use 16.17.1`

**Actual Behavior:**

![image](https://user-images.githubusercontent.com/114364831/211403280-ec2012fb-9cf8-490d-b66e-18e0b16cf3e2.png)

![image](https://user-images.githubusercontent.com/114364831/211403410-c466142f-0055-44d7-aa14-84aeb083facf.png)

![image](https://user-images.githubusercontent.com/114364831/211405017-5f6992a7-a553-41f4-a950-6e90fa582b6d.png)

**Desktop:**
 - OS: Windows

**Comment by coreybutler** [comment]
Are you behind a proxy?

If `nvm list available` returns an empty table, then it is not receiving a response from the [release URL](https://nodejs.org/download/release/index.json). A proxy could block this request. This would also explain the notice about v16.17.1 not being released yet and why nvm install latest would fail, since nvm4w won't know any releases exist without the release data.

If a prior Node.js installation exists, `node -v` will return a version. This happens when the Node.js bin path precedes NVM4W in the `PATH`, or if the NVM4W symlink contains no binary (and is the reason the README recommend uninstalling Node before installing NVM4W).

**Comment by jjlin526** [comment]
I turned off my VPN proxy and the issue is resolved. Thank you!
