### ISSUE TITLE
'nvm use' does not update Node.js version

### ISSUE THREAD

**Issue by jjlin526** [coreybutler/nvm-windows#920]
**Issue:**
`nvm use` does not change the Node.js version

**How To Reproduce:**
1. Run the command: `nvm use v16.17.1` which outputs `Now using node v16.17.1 (64-bit)`
2. Run the command: `node -v` which outputs `v19.4.0`

**Expected Behavior:**
Node.js version should be updated

**Screenshot:**
![image](https://user-images.githubusercontent.com/114364831/214645206-0cfc9b72-08d4-46bc-ae89-4c95c068077f.png)

**Desktop:**
 - OS: Windows

**Comment by afif-malghani** [comment]
I am having the same issue, did you install v19.4.0 with nvm as well?
I installed v18.13.0 from the installer and v14.17.3 from nvm.
I can not switch to v14.17.3, neither can I use v14.17.3 if I uninstall v18.13.0.

The versions installed by nvm install are there in the nvm root directory but nvm can not create a symlink to them in Program Files.
I have tried using NVM in admin cmd as well as changing permissions to Program Files, nothing seems to work.

**Comment by coreybutler** [comment]
@jjlin526 - either there is a conflicting version of Node installed (most likely) or the user doesn't have permissions to change the symlink. See [why-do-i-need-to-uninstall-nodejs-before-installing-nvm-for-windows](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-do-i-need-to-uninstall-nodejs-before-installing-nvm-for-windows) and [permissions](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145).

@afif-malghani I think you may be using [nvm-sh](https://github.com/nvm-sh/nvm) because `nvm config` is not a valid command in NVM4W.
