### ISSUE TITLE
NVM 1.1.10 -- ERROR open \settings.txt

### ISSUE THREAD

**Issue by DigDugIA** [coreybutler/nvm-windows#929]
Greetings. Thanks for all your time supporting NVM.

I just downloaded and ran the install EXE for NVM 1.1.10. I do the nvm -v and get that version number back. I do nvm by itself and get the help info. When I try the "nvm install latest" command I get this back.

ERROR open \settings.txt: The system cannot find the file specified.

I can see all the files listed at the top of this Issue.

Directory Image:
![image](https://user-images.githubusercontent.com/14084100/218594067-40c7490c-4619-4e03-bcff-5d002a0ad682.png)

Not sure what to do next. Need to get NPM installed, so I can run a OpenAPI generator to get a C# API library for a company I need to do API calls into.

Thanks.

**Comment by coreybutler** [comment]
Where did you install NVM4W? The screenshot shows the settings.txt file and nvm.exe is running (otherwise the version would fail). This suggests to me that perhaps you've installed in `C:\Program Files` and you're trying to run NVM4W with a non-privileged account. Windows will block access to some files in protected directories (`C:\Program Files` is one). So, you may just need to run your command prompt as administrator.

**Comment by DigDugIA** [comment]
Admin CMD window did the trick.  I have NVM installed to "C:\Users\DigDugIA\AppData\Roaming\nvm".   And I'm logged as that user, so guessing it was a windows protection hit.    

Was able to finish the NVM install of latest and the NPM install of OpenAPI Generator CLI just finished successfully.  

Thanks!
