### ISSUE TITLE
Error occurrs wehn using nvm inside powershell of VS Code

### ISSUE THREAD

**Issue by SnGmng** [coreybutler/nvm-windows#934]
**Issue:**
If i use powershell within VS Code, nvm doesnt work. If i use a seperate powershell window, it works as normal. 
```
PS D:\projects> npm
&: C:\Users\user\AppData\Roaming\npm\npm.ps1:24:7
Line |
  24 |      & "node$exe"  "$basedir/node_modules/npm/bin/npm-cli.js" $args
     |        ~~~~~~~~~~
     | The term 'node.exe' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that    
     | the path is correct and try again.
```

**How To Reproduce:**
1. Go to VS Code
2. Open new Powershell Terminal
3. Try to use npm/node

**Desktop:**
 - OS: Windows 11

**Comment by coreybutler** [comment]
This is a partially-known issue. 

If you run VS Code with the proper permissions (i.e. admin and/or elevated, developer mode enabled, etc), it can work, but VS Code needs to launch Powershell with the right user context. If not, NVM4W will trigger UAC prompts for you (i.e. temporarily grant access), but VS Code has (sometimes) blocked these in the past. That said, you'd normally see a permissions issue. 

You're experiencing a pathing issue, i.e. the node executable can't be found. I suspect that VS Code may be running with a user that doesn't have NVM4W in it's `PATH`. If you can run `node -v` from Powershell within VS Code and get a response, the PATH is correct. Otherwise, something else is going on.

**Comment by SnGmng** [comment]
After reinstalling/updating VS Code, it works now
