### ISSUE TITLE
Setup stuck in prompt loop

### ISSUE THREAD

**Issue by steelbath** [coreybutler/nvm-windows#940]
With the setup.exe, if it finds a previous installed version it will ask if it should track that version and then that everything in the folder that contains the version will be deleted, then it will start over if i confirm both. Eventually got it to installed by pressing no and on "exit setup" no again. 

After install the current version was tracked as by "nvm current" but nvm list would return "No installations recognized".

**Comment by coreybutler** [comment]
Please see the following:

- [Uninstall Existing Node Installation Before Installing NVM4W](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#uninstall-existing-node-installation-before-installing-nvm4w)
- [Why do I Need to Uninstall Node.js Before Installing NVM for Windows?](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-do-i-need-to-uninstall-nodejs-before-installing-nvm-for-windows)

> _After install the current version was tracked as by "nvm current" but nvm list would return "No installations recognized"._

`nvm current` just runs `node -v`. Windows does this by running the first `node.exe` it finds in the `PATH`. In your case, I suspect the old installation wasn't actually uninstalled, so you're still seeing the original installation. When you run `nvm ls`, it scans the NVM root directory for installations. Since your original installation didn't actually get moved, this directory would be empty. That's why it says there aren't any installations.
