### ISSUE TITLE
[2024/04/14]: [nvm install --lts]

### ISSUE THREAD

**Issue by bennycode** [coreybutler/nvm-windows#964]
The classic [nvm](https://github.com/nvm-sh/nvm) has a command called `nvm install --lts` to install the latest LTS version of Node. With `nvm-windows` the command is called `nvm install lts`. Would it be possible to also support an alias for `nvm install --lts` so that commands are similar?

**Comment by coreybutler** [comment]
Possible, yes. But I don't intend to do this. First, this project does not aim for parity with nvm-sh. Second, I would argue that a flag doesn't make sense when specifying an argument (i.e. you don't run `nvm install --19.9.0`). There is a historical [reason why](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported) we don't aim for nvm parity, but the more pressing reason is due to the [freeze](https://github.com/coreybutler/nvm-windows/wiki/Runtime).

**Comment by bennycode** [comment]
Thanks for your prompt response. I appreciate your explanation, and I understand the reasoning behind it. I came across this issue while recording programming tutorials to learn TypeScript. As a part of my tutorial series, I'm explaining how to install Node.js using nvm or nvm-windows.  In doing so, I discovered the subtle difference. No problem at all, I'll simply inform the audience about the difference.
