### ISSUE TITLE
[Issue]: nvm can be disabled system-wide by any non-admin

### ISSUE THREAD

**Issue by yilmazdurmaz** [coreybutler/nvm-windows#983]
### What happened?

I had this in another issue (started as a feature request) but it stays stale probably without a work on my last comment. https://github.com/coreybutler/nvm-windows/issues/761

here is the problem: neither `nvm off` nor `nvm use ...` checks for admin rights and thus any user can disable node installation system-wide, whether intentional or not.

(unintentional way) - I saw there is an added feature that start a UAC prompt. this is great as now `nvm use ...` asks for admin access, but the answer is not checked whether access is granted and the hard link to the node directory is just removed causing the system-wide havoc.

(intentional way) - similarly, `nvm off` does not check whether the user has admin access and directly remove the hardlink to the node directory.

### What did you expect to happen?

"nvm first tries to see if it can run a command without privilege"

this simplified statement might be good for any other kind of operation. But it is definitely not for when you are dealing with the hardlink to the node installation, especially the two situations I described above.

`nvm off` and `nvm use ...` should never try to comply to the above statement. instead these two commands must always check if the user has the privilege to remove the hardlink of the node directory.

BONUS: `nvm on` opens a UAC prompt, but similarly, if the privilege is not given, the result is misleadingly show `nvm enabled now using ...` while it actually failed to activate

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Other, please describe

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
explanations on the line of each command
`
c:\WorkSpace>nvm off  #(no UAC prompt, executed immediately)
nvm disabled

c:\WorkSpace>nvm on  #(UAC comes up, but answered "NO", result is misleading)
nvm enabled
Now using node v20.2.0 (64-bit)

c:\WorkSpace>node --version  #(not active because answered "NO")
'node' is not recognized as an internal or external command,
operable program or batch file.

c:\WorkSpace>nvm on  #(UAC comes up, answered "YES")
nvm enabled
Now using node v20.2.0 (64-bit)

c:\WorkSpace>node --version  #(node is active because answered "YES")
v20.2.0

c:\WorkSpace>nvm use 20.2.0  #(killer action, try to use same/another version, answer "NO" to UAC to simulate no privilege)
Now using node v20.2.0 (64-bit)

c:\WorkSpace>node --version  #(someone just killed the node unintentionally(!) with above action)
'node' is not recognized as an internal or external command,
operable program or batch file.

````
```


### Debug Output

```Shell
c:\WorkSpace>nvm debug
durmaz is not using admin or elevated rights.

C:\Windows\System32\cmd.exe - nvm  debug
Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.11
NVM4W Path:         C:\DevTools\nvm\nvm.exe
NVM4W Settings:     C:\DevTools\nvm\settings.txt
NVM_HOME:           C:\DevTools\nvm
NVM_SYMLINK:        C:\DevTools\nodejs
Node Installations: C:\DevTools\nvm

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

PROBLEMS DETECTED
-----------------
"C:\Windows\System32\cmd.exe - nvm  debug" is not an officially supported shell. Some features may not work as expected.



Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
Just to clarify, there are no hard links created by NMV4W. Everything is a soft link.

If Node is installed system-wide, then any credentialed user should have the ability to do this. This is the original intention of the Node project, as evidenced by the fact an "official" installer only allows one version at a time. If there were no version manager, users would have to have permission to install/uninstall Node. That's the same environment NVM4W is providing.

At a technical level, when `nvm off` is run, it clears a symlink. When `nvm use` is run, the symlink is updated. If a user has symlink management permissions, they will be able to perform either of these actions, regardless of whether they are an admin. In other words, they could manually remove the symlink (delete the symlink) or they could change it (ala `mklink`), even if they didn't use NVM4W to do it. NVM4W isn't managing the permissions, Windows is. This is why NVM4W attempts to run the commands without a UAC prompt. If the command fails, it retries with elevation, which _triggers Windows_ to trigger the UAC prompt. This is merely a convenience provided by NVM4W.

Unfortunately, the UAC prompt does not return the selected status, so NVM4W cannot tell if a user selected "cancel". However; if the user selects cancel, the operation will not actually be performed. NVM4W will tell you it was successful because the "prompt was successful".... it just doesn't know the result of the prompt (ok or cancel).

As a simple version switcher, I don't think it's NVM4W's place to determine what a user can/cannot do... that is the responsibility of the operating system. Determining how NVM4W applies new versions has had a very split response amongst the community. Some want stricter controls while others want none at all. Ultimately, I would like to give developers the choice. However; that is more about environment management than just version switching. In other words, people want to manage their environments their way... there's no one size fits all.

I don't plan to change the existing behavior of NVM4W because the project scope starts creeping into environment management. However; I am still very interested and sympathetic to use cases where more guardrails are available to prevent developers from doing big things unintentionally or without oversight. This challenge is better suited for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) though. In other words, I'm happy to have a conversation about the use cases identified here, but any implementation will end up in Runtime, not NVM4W.

I'm closing this as an issue, but am happy to discuss it further in the [discussions](https://github.com/coreybutler/nvm-windows/discussions).

**Comment by yilmazdurmaz** [comment]
> Just to clarify, there are no hard links created by NMV4W. Everything is a soft link.

My bad! I thought it was a hard link because of the requirement to be an admin and never check truly.

and it is also weird because you are only changing a link in a user-accessible folder and it needs privilege. (both nvm and nodejs folders under `c:\devtools`). what else is changing?

Anyways, this one is new for me, so I should find some other free time to learn about it. Only then I can join the discussion :)
> This challenge is better suited for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) though

thanks for sharing your time for the answer.
