### ISSUE TITLE
[Issue]: nvm doesn't create folders if they don't exist

### ISSUE THREAD

**Issue by Wazarr94** [coreybutler/nvm-windows#985]
### What happened?

I installed nvm. I tried to change the location of both the home and symlink folder from my C drive to my new E drive which is pretty much empty. I already had the AppData/Roaming folder in my E drive after installing other programs, so I didn't have an issue with the Home folder.

However, I did not have a Program Files folder, and this resulted in the use command not working at all.
After creating by hand the E:/Program Files/nodejs folder, all went well.

### What did you expect to happen?

.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

Western European

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

Yes

**Comment by coreybutler** [comment]
I'm closing this since it isn't a bug, but I think it's good this was documented for others who try to do the same thing. 

A real directory root is required by Windows. If you specify `E:\Program Files\nodejs` as the `NVM_SYMLINK`, the root must exist. In this case, that means `E:\Program Files` must exist.
